# backend/tests/test_growth_center.py
"""成长档案中心 API 测试 — 认证 / 轨迹幂等 / 档案聚合 / 实时统计。"""

from datetime import datetime, timedelta, timezone

from tests.test_action_center import _checkin, _create_action


# ----------------------------------------------------------------------
# 认证要求
# ----------------------------------------------------------------------
class TestAuthRequired:
    def test_trajectory_requires_auth(self, client):
        assert client.get("/api/growth/trajectory").status_code == 401

    def test_create_trajectory_requires_auth(self, client):
        resp = client.post(
            "/api/growth/trajectory",
            json={
                "event_type": "milestone",
                "event_payload": {},
                "occurred_at": datetime.now(timezone.utc).isoformat(),
            },
        )
        assert resp.status_code == 401

    def test_archive_requires_auth(self, client):
        assert client.get("/api/growth/archive").status_code == 401

    def test_stats_requires_auth(self, client):
        assert client.get("/api/growth/stats").status_code == 401


# ----------------------------------------------------------------------
# 成长轨迹事件流
# ----------------------------------------------------------------------
class TestTrajectory:
    def _post(self, client, auth_headers, payload):
        return client.post("/api/growth/trajectory", headers=auth_headers, json=payload)

    def test_create_ok(self, auth_headers, client):
        resp = self._post(
            client, auth_headers,
            {
                "event_type": "milestone",
                "event_payload": {"milestone": "拿到了第一份实习"},
                "occurred_at": datetime.now(timezone.utc).isoformat(),
                "source_event_id": "evt-001",
            },
        )
        assert resp.status_code == 200, resp.text
        body = resp.json()
        assert body["event_type"] == "milestone"
        assert body["user_id"]  # UUID 已注入
        assert body["source_event_id"] == "evt-001"

    def test_source_event_id_idempotent(self, auth_headers, client):
        """相同 source_event_id 重复提交 → 返回同一事件，不新增。"""
        payload = {
            "event_type": "milestone",
            "event_payload": {"x": 1},
            "occurred_at": datetime.now(timezone.utc).isoformat(),
            "source_event_id": "evt-dup",
        }
        first = self._post(client, auth_headers, payload).json()
        second = self._post(client, auth_headers, payload).json()
        assert first["id"] == second["id"]
        resp = client.get("/api/growth/trajectory", headers=auth_headers)
        assert resp.json()["total"] == 1

    def test_list_sorted_desc(self, auth_headers, client):
        base = datetime.now(timezone.utc)
        self._post(client, auth_headers, {
            "event_type": "milestone",
            "event_payload": {"n": 1},
            "occurred_at": (base - timedelta(minutes=2)).isoformat(),
            "source_event_id": "evt-a",
        })
        self._post(client, auth_headers, {
            "event_type": "review_completed",
            "event_payload": {"n": 2},
            "occurred_at": base.isoformat(),
            "source_event_id": "evt-b",
        })
        items = client.get("/api/growth/trajectory", headers=auth_headers).json()["items"]
        assert [i["event_type"] for i in items] == ["review_completed", "milestone"]


# ----------------------------------------------------------------------
# 档案聚合
# ----------------------------------------------------------------------
class TestArchive:
    def test_empty_archive_autogenerated(self, auth_headers, client):
        """无行动时档案自动聚合生成全零快照。"""
        resp = client.get("/api/growth/archive", headers=auth_headers)
        assert resp.status_code == 200
        body = resp.json()
        assert body["total_actions"] == 0
        assert body["completed_actions"] == 0
        assert body["action_completion_rate"] == 0.0
        assert body["weighted_action_score"] == 0.0
        assert body["archive_status"] == "ACTIVE"
        assert body["updated_at"]  # 契约 updated_at 已映射

    def test_archive_aggregates_actions(self, auth_headers, client):
        """2 个行动（权重 1+15），完成权重 15 → 完成率 0.5、加权分 93.75。"""
        a1 = _create_action(client, auth_headers, action_type="read_article")  # weight 1
        a2 = _create_action(client, auth_headers, action_type="mock_interview")  # weight 15
        _checkin(client, auth_headers, a2["id"])

        resp = client.get("/api/growth/archive", headers=auth_headers)
        body = resp.json()
        assert body["total_actions"] == 2
        assert body["completed_actions"] == 1
        assert body["action_completion_rate"] == 0.5
        assert body["weighted_action_score"] == 93.75
        assert body["streak_days"] == 1
        assert a1["id"] != a2["id"]

    def test_refresh_endpoint(self, auth_headers, client):
        a = _create_action(client, auth_headers)
        resp = client.put("/api/growth/archive/refresh", headers=auth_headers)
        assert resp.status_code == 200
        body = resp.json()
        assert body["total_actions"] == 1
        assert body["completed_actions"] == 0
        # 打卡后再刷新
        _checkin(client, auth_headers, a["id"])
        resp = client.put("/api/growth/archive/refresh", headers=auth_headers)
        body = resp.json()
        assert body["completed_actions"] == 1

    def test_refresh_does_not_require_path_user_id(self, auth_headers, client):
        """旧契约 /archive/{user_id}/refresh 已改为当前用户，无越权路径参数。"""
        resp = client.put("/api/growth/archive/refresh", headers=auth_headers)
        assert resp.status_code == 200


# ----------------------------------------------------------------------
# 实时统计
# ----------------------------------------------------------------------
class TestStats:
    def test_empty_stats(self, auth_headers, client):
        resp = client.get("/api/growth/stats", headers=auth_headers)
        assert resp.status_code == 200
        body = resp.json()
        assert body["total_actions"] == 0
        assert body["action_completion_rate"] == 0.0
        assert body["current_streak_days"] == 0

    def test_stats_after_actions(self, auth_headers, client):
        a1 = _create_action(client, auth_headers)
        _create_action(client, auth_headers, action_type="finish_course")
        _checkin(client, auth_headers, a1["id"])
        body = client.get("/api/growth/stats", headers=auth_headers).json()
        assert body["total_actions"] == 2
        assert body["completed_actions"] == 1
        assert body["action_completion_rate"] == 0.5
        assert body["current_streak_days"] == 1
        assert body["longest_streak_days"] == 1
