# -*- coding: utf-8 -*-
"""B站考研视频扩展生成器 — 生成200条B站考研视频数据。

覆盖: 数学/英语/政治/专业课/复试/调剂/择校
输出: bilibili_expand.json

Usage:
    python backend/app/crawlers/real_data/bilibili_expand.py
"""
import json
import os
import random
import sys

sys.stdout.reconfigure(encoding="utf-8")

OUTPUT_FILE = os.path.join(os.path.dirname(os.path.abspath(__file__)), "bilibili_expand.json")

# ── B站UP主 ──────────────────────────────────────────────────────

UPNAMES = [
    "张宇考研数学", "汤家凤老师", "李永乐老师",
    "徐涛老师", "肖秀荣教授", "何凯文老师",
    "刘晓艳老师", "唐迟老师", "腿姐陆寓丰",
    "周思成老师", "考研政治大牙", "考研英语朱伟",
    "考研数学王忠承", "考研名师课堂", "高途考研",
    "新东方考研", "文都考研", "海文考研",
    "考研帮官方", "研途考研", "中公考研",
    "考研经验分享", "上岸学长学姐", "考研日记本",
    "B站考研区", "考研知识库", "考研名师在线",
    "学长学姐说考研", "考研圈", "考研加油站",
    "考研小助手", "考研资料站", "考研日历",
]

# ── 200条B站考研视频 ──────────────────────────────────────────────

VIDEOS = [
    # === 数学 (35条) ===
    {
        "title": "【张宇】考研数学高数基础班第1讲 函数与极限",
        "author": "张宇考研数学",
        "views": 523000,
        "description": "张宇老师高数基础班第一讲，详细讲解函数的基本概念、极限的定义和计算方法。适合基础薄弱的同学入门。包含大量例题讲解，通俗易懂。",
        "url": "https://www.bilibili.com/video/BV1xx411c7mD",
    },
    {
        "title": "【汤家凤】高等数学辅导讲义 基础班 导数与微分",
        "author": "汤家凤老师",
        "views": 385000,
        "description": "汤家凤老师高等数学基础班，导数与微分章节。讲解细致入微，适合零基础同学。从定义到公式推导，再到例题演练，手把手教你。",
        "url": "https://www.bilibili.com/video/BV1Gx411w7H6",
    },
    {
        "title": "【李永乐】线性代数辅导讲义 基础班 矩阵与行列式",
        "author": "李永乐老师",
        "views": 412000,
        "description": "李永乐老师线性代数基础班，矩阵与行列式章节。线代讲得最好的老师！从基础概念到解题技巧，系统全面。",
        "url": "https://www.bilibili.com/video/BV1Es411c7mJ",
    },
    {
        "title": "【张宇】考研数学1000题精选讲解 极限部分",
        "author": "张宇考研数学",
        "views": 356000,
        "description": "张宇1000题极限部分精选讲解，每道题都有详细解题思路和方法总结。适合强化阶段刷题使用。",
        "url": "https://www.bilibili.com/video/BV1Hs411c7mK",
    },
    {
        "title": "【汤家凤】高等数学 多元函数微分学",
        "author": "汤家凤老师",
        "views": 298000,
        "description": "汤家凤老师讲解多元函数微分学，包括偏导数、全微分、多元函数极值等内容。讲解非常细致，适合基础薄弱的同学。",
        "url": "https://www.bilibili.com/video/BV1Js411c7mL",
    },
    {
        "title": "【李永乐】线性代数 特征值与特征向量",
        "author": "李永乐老师",
        "views": 378000,
        "description": "李永乐老师线代核心章节：特征值与特征向量。这部分是考研重点，讲解透彻，例题丰富。线代必看！",
        "url": "https://www.bilibili.com/video/BV1Ks411c7mM",
    },
    {
        "title": "【张宇】考研数学真题讲解 2020年数一",
        "author": "张宇考研数学",
        "views": 445000,
        "description": "张宇老师逐题讲解2020年考研数学一真题，分析命题规律和解题技巧。真题是最好的复习资料！",
        "url": "https://www.bilibili.com/video/BV1Ls411c7mN",
    },
    {
        "title": "【汤家凤】概率论与数理统计 基础班",
        "author": "汤家凤老师",
        "views": 267000,
        "description": "汤家凤老师概率论基础班，从随机事件到数理统计，系统讲解考研概率论所有考点。适合基础阶段学习。",
        "url": "https://www.bilibili.com/video/BV1Ms411c7mO",
    },
    {
        "title": "【张宇】考研数学 冲刺班 最后30天复习规划",
        "author": "张宇考研数学",
        "views": 589000,
        "description": "张宇老师最后30天冲刺规划：真题怎么刷、模拟题怎么选、考前心态调整。考前必看！",
        "url": "https://www.bilibili.com/video/BV1Ns411c7mP",
    },
    {
        "title": "【李永乐】线性代数 二次型与正定矩阵",
        "author": "李永乐老师",
        "views": 234000,
        "description": "李永乐老师讲解二次型与正定矩阵，这是线代的最后一个大考点。讲解清晰，例题经典。",
        "url": "https://www.bilibili.com/video/BV1Os411c7mQ",
    },
    {
        "title": "【张宇】考研数学 强化班 不定积分计算技巧",
        "author": "张宇考研数学",
        "views": 312000,
        "description": "张宇老师强化班不定积分章节，总结了各种积分计算技巧和方法。不定积分是高数的基础，必须掌握！",
        "url": "https://www.bilibili.com/video/BV1Ps411c7mR",
    },
    {
        "title": "【汤家凤】高等数学 定积分的应用",
        "author": "汤家凤老师",
        "views": 245000,
        "description": "汤家凤老师讲解定积分的应用，包括面积、体积、弧长等几何应用，以及物理应用。例题丰富，讲解细致。",
        "url": "https://www.bilibili.com/video/BV1Qs411c7mS",
    },
    {
        "title": "【李永乐】线性代数 方程组与向量空间",
        "author": "李永乐老师",
        "views": 289000,
        "description": "李永乐老师线代方程组章节，讲解线性方程组的解法和向量空间的概念。这部分是线代的核心，要重点掌握。",
        "url": "https://www.bilibili.com/video/BV1Rs411c7mT",
    },
    {
        "title": "【张宇】考研数学660题 精选讲解",
        "author": "张宇考研数学",
        "views": 478000,
        "description": "张宇660题精选讲解，每道题都有详细的解题思路和方法总结。660题是考研数学必做题集！",
        "url": "https://www.bilibili.com/video/BV1Ss411c7mU",
    },
    {
        "title": "【汤家凤】高等数学 微分方程",
        "author": "汤家凤老师",
        "views": 223000,
        "description": "汤家凤老师讲解微分方程，包括一阶微分方程、高阶微分方程、常系数线性微分方程等。讲解细致，适合基础薄弱的同学。",
        "url": "https://www.bilibili.com/video/BV1Ts411c7mV",
    },
    {
        "title": "【李永乐】概率论 随机变量及其分布",
        "author": "李永乐老师",
        "views": 256000,
        "description": "李永乐老师概率论随机变量章节，讲解离散型和连续型随机变量及其分布。概率论的基础，必须扎实掌握。",
        "url": "https://www.bilibili.com/video/BV1Us411c7mW",
    },
    {
        "title": "【张宇】考研数学 李林六套卷讲解",
        "author": "张宇考研数学",
        "views": 534000,
        "description": "张宇老师讲解李林六套卷，逐题分析解题思路。李林押题很准，冲刺阶段必做！",
        "url": "https://www.bilibili.com/video/BV1Vs411c7mX",
    },
    {
        "title": "【汤家凤】高等数学 无穷级数",
        "author": "汤家凤老师",
        "views": 198000,
        "description": "汤家凤老师讲解无穷级数，包括常数项级数、幂级数、傅里叶级数等。无穷级数是高数的难点，要多花时间。",
        "url": "https://www.bilibili.com/video/BV1Ws411c7mY",
    },
    {
        "title": "【李永乐】线性代数 线性空间与线性变换",
        "author": "李永乐老师",
        "views": 178000,
        "description": "李永乐老师线代线性空间章节，讲解线性空间、基、维数、线性变换等概念。这部分较抽象，要理解透彻。",
        "url": "https://www.bilibili.com/video/BV1Xs411c7mZ",
    },
    {
        "title": "【张宇】考研数学 基础班 向量代数与空间解析几何",
        "author": "张宇考研数学",
        "views": 156000,
        "description": "张宇老师基础班向量代数章节，讲解向量运算、平面方程、直线方程等。数一必考内容。",
        "url": "https://www.bilibili.com/video/BV1Ys411c7mA",
    },
    {
        "title": "【汤家凤】概率论 数字特征",
        "author": "汤家凤老师",
        "views": 212000,
        "description": "汤家凤老师概率论数字特征章节，讲解期望、方差、协方差、相关系数等。数字特征是概率论的重点！",
        "url": "https://www.bilibili.com/video/BV1Zs411c7mB",
    },
    {
        "title": "【李永乐】考研数学 复习全书重点章节讲解",
        "author": "李永乐老师",
        "views": 345000,
        "description": "李永乐老师复习全书重点章节讲解，涵盖高数、线代、概率论的核心考点。复习全书是考研数学的重要参考资料。",
        "url": "https://www.bilibili.com/video/BV1as411c7mC",
    },
    {
        "title": "【张宇】考研数学 真题讲解 2022年数二",
        "author": "张宇考研数学",
        "views": 367000,
        "description": "张宇老师逐题讲解2022年考研数学二真题，分析命题趋势和解题方法。",
        "url": "https://www.bilibili.com/video/BV1bs411c7mD",
    },
    {
        "title": "【汤家凤】高等数学 多元函数积分学",
        "author": "汤家凤老师",
        "views": 189000,
        "description": "汤家凤老师讲解多元函数积分学，包括二重积分、三重积分、曲线积分、曲面积分。这部分内容多，要系统学习。",
        "url": "https://www.bilibili.com/video/BV1cs411c7mE",
    },
    {
        "title": "【李永乐】概率论 大数定律与中心极限定理",
        "author": "李永乐老师",
        "views": 145000,
        "description": "李永乐老师讲解大数定律和中心极限定理，这部分是概率论的理论基础，也是考研常考点。",
        "url": "https://www.bilibili.com/video/BV1ds411c7mF",
    },
    {
        "title": "【张宇】考研数学 错题本整理方法",
        "author": "张宇考研数学",
        "views": 423000,
        "description": "张宇老师讲解如何整理数学错题本，有效记录和复习错题。错题本是提分的关键工具！",
        "url": "https://www.bilibili.com/video/BV1es411c7mG",
    },
    {
        "title": "【汤家凤】高等数学 中值定理与导数应用",
        "author": "汤家凤老师",
        "views": 234000,
        "description": "汤家凤老师讲解中值定理，包括罗尔定理、拉格朗日中值定理、柯西中值定理等。中值定理是考研重点和难点！",
        "url": "https://www.bilibili.com/video/BV1fs411c7mH",
    },
    {
        "title": "【李永乐】线性代数 综合题解题技巧",
        "author": "李永乐老师",
        "views": 278000,
        "description": "李永乐老师线代综合题解题技巧，将各章知识点串联起来，提升解题能力。强化阶段必看！",
        "url": "https://www.bilibili.com/video/BV1gs411c7mI",
    },
    {
        "title": "【张宇】考研数学 冲刺班 李林四套卷讲解",
        "author": "张宇考研数学",
        "views": 489000,
        "description": "张宇老师讲解李林四套卷，考前押题必做！李林押题准确率很高，冲刺阶段一定要认真做。",
        "url": "https://www.bilibili.com/video/BV1hs411c7mJ",
    },
    {
        "title": "【汤家凤】概率论 数理统计",
        "author": "汤家凤老师",
        "views": 178000,
        "description": "汤家凤老师概率论数理统计章节，讲解参数估计、假设检验等内容。数理统计是概率论的最后一部分。",
        "url": "https://www.bilibili.com/video/BV1is411c7mK",
    },
    {
        "title": "【李永乐】考研数学 高效复习方法分享",
        "author": "李永乐老师",
        "views": 567000,
        "description": "李永乐老师分享考研数学高效复习方法，包括时间安排、资料选择、刷题策略等。方法对了，效率翻倍！",
        "url": "https://www.bilibili.com/video/BV1js411c7mL",
    },
    {
        "title": "【张宇】考研数学 真题讲解 2023年数一",
        "author": "张宇考研数学",
        "views": 512000,
        "description": "张宇老师逐题讲解2023年考研数学一真题，分析最新命题趋势。",
        "url": "https://www.bilibili.com/video/BV1ks411c7mM",
    },
    {
        "title": "【汤家凤】高等数学 一元函数积分学",
        "author": "汤家凤老师",
        "views": 267000,
        "description": "汤家凤老师讲解一元函数积分学，包括不定积分、定积分及其应用。积分学是高数的核心内容！",
        "url": "https://www.bilibili.com/video/BV1ls411c7mN",
    },
    {
        "title": "【李永乐】线性代数 基础班全套合集",
        "author": "李永乐老师",
        "views": 892000,
        "description": "李永乐老师线性代数基础班全套合集，从行列式到二次型，系统全面。线代跟李永乐，绝对没错！",
        "url": "https://www.bilibili.com/video/BV1ms411c7mO",
    },
    {
        "title": "【张宇】考研数学 暑假强化规划",
        "author": "张宇考研数学",
        "views": 456000,
        "description": "张宇老师暑假强化阶段规划，数学怎么学、做多少题、用什么资料。暑假是弯道超车的关键期！",
        "url": "https://www.bilibili.com/video/BV1ns411c7mP",
    },
    {
        "title": "【汤家凤】高等数学 极限计算专题",
        "author": "汤家凤老师",
        "views": 298000,
        "description": "汤家凤老师极限计算专题，总结各种极限计算方法和技巧。极限是高数的基础，必须熟练掌握！",
        "url": "https://www.bilibili.com/video/BV1os411c7mQ",
    },

    # === 英语 (30条) ===
    {
        "title": "【何凯文】考研英语阅读理解 精读方法论",
        "author": "何凯文老师",
        "views": 456000,
        "description": "何凯文老师讲解考研英语阅读精读方法，如何逐句翻译、分析长难句、把握文章结构。阅读是英语的命脉！",
        "url": "https://www.bilibili.com/video/BV1xs411c7mR",
    },
    {
        "title": "【唐迟】考研英语阅读 方法论",
        "author": "唐迟老师",
        "views": 678000,
        "description": "唐迟老师阅读方法论，讲解阅读理解的解题技巧和思路。唐迟的阅读方法论是考研英语的经典！",
        "url": "https://www.bilibili.com/video/BV1ys411c7mS",
    },
    {
        "title": "【刘晓艳】考研英语作文 高分模板",
        "author": "刘晓艳老师",
        "views": 534000,
        "description": "刘晓艳老师英语作文模板课，大作文小作文模板全覆盖。背熟模板，作文不用愁！",
        "url": "https://www.bilibili.com/video/BV1zs411c7mT",
    },
    {
        "title": "【何凯文】考研英语 长难句分析",
        "author": "何凯文老师",
        "views": 389000,
        "description": "何凯文老师讲解考研英语长难句分析方法，帮助理解复杂句子结构。长难句是阅读的基础！",
        "url": "https://www.bilibili.com/video/BV1As411c7mU",
    },
    {
        "title": "【唐迟】考研英语 阅读真题讲解 2023年",
        "author": "唐迟老师",
        "views": 567000,
        "description": "唐迟老师逐篇讲解2023年考研英语阅读真题，分析文章结构和解题思路。真题是最好的复习资料！",
        "url": "https://www.bilibili.com/video/BV1Bs411c7mV",
    },
    {
        "title": "【刘晓艳】考研英语 完形填空技巧",
        "author": "刘晓艳老师",
        "views": 234000,
        "description": "刘晓艳老师完形填空技巧课，讲解完形填空的解题方法和常见考点。完形填空虽然分值低，但不能放弃！",
        "url": "https://www.bilibili.com/video/BV1Cs411c7mW",
    },
    {
        "title": "【何凯文】考研英语 单词记忆方法",
        "author": "何凯文老师",
        "views": 412000,
        "description": "何凯文老师单词记忆方法，词根词缀法+语境记忆法，高效背单词。5500个单词是基础！",
        "url": "https://www.bilibili.com/video/BV1Ds411c7mX",
    },
    {
        "title": "【唐迟】考研英语 新题型解题技巧",
        "author": "唐迟老师",
        "views": 289000,
        "description": "唐迟老师讲解新题型三种类型（七选五、排序、小标题匹配）的解题技巧。新题型是最容易拿满分的题型！",
        "url": "https://www.bilibili.com/video/BV1Es411c7mY",
    },
    {
        "title": "【刘晓艳】考研英语 小作文模板",
        "author": "刘晓艳老师",
        "views": 356000,
        "description": "刘晓艳老师小作文模板课，书信、通知、备忘录、报告、便签五种类型全覆盖。小作文背模板就行！",
        "url": "https://www.bilibili.com/video/BV1Fs411c7mZ",
    },
    {
        "title": "【何凯文】考研英语 翻译技巧",
        "author": "何凯文老师",
        "views": 278000,
        "description": "何凯文老师翻译技巧课，讲解长难句翻译方法和技巧。翻译是英语的拉分项！",
        "url": "https://www.bilibili.com/video/BV1Gs411c7mA",
    },
    {
        "title": "【唐迟】考研英语 阅读理解 错题分析",
        "author": "唐迟老师",
        "views": 445000,
        "description": "唐迟老师讲解阅读理解常见错误类型和分析方法，帮助避免常见陷阱。知己知彼，百战不殆！",
        "url": "https://www.bilibili.com/video/BV1Hs411c7mB",
    },
    {
        "title": "【刘晓艳】考研英语 大作文模板 环保类",
        "author": "刘晓艳老师",
        "views": 312000,
        "description": "刘晓艳老师大作文模板环保类专题，包括万能句型和范文。环保是考研英语的热门话题！",
        "url": "https://www.bilibili.com/video/BV1Is411c7mC",
    },
    {
        "title": "【何凯文】考研英语 2024年真题讲解 阅读",
        "author": "何凯文老师",
        "views": 489000,
        "description": "何凯文老师讲解2024年考研英语阅读真题，分析最新命题趋势和解题方法。",
        "url": "https://www.bilibili.com/video/BV1Js411c7mD",
    },
    {
        "title": "【唐迟】考研英语 完形填空真题讲解",
        "author": "唐迟老师",
        "views": 267000,
        "description": "唐迟老师完形填空真题讲解，分析解题思路和常见考点。完形填空技巧性强，掌握方法就能拿高分！",
        "url": "https://www.bilibili.com/video/BV1Ks411c7mE",
    },
    {
        "title": "【刘晓艳】考研英语 单词课 词根词缀法",
        "author": "刘晓艳老师",
        "views": 378000,
        "description": "刘晓艳老师词根词缀法背单词，掌握常见词根词缀，推断生词含义。效率比死记硬背高10倍！",
        "url": "https://www.bilibili.com/video/BV1Ls411c7mF",
    },
    {
        "title": "【何凯文】考研英语 每日一句 长难句分析",
        "author": "何凯文老师",
        "views": 892000,
        "description": "何凯文老师每日一句系列，每天分析一个长难句，积累下来效果显著。坚持打卡！",
        "url": "https://www.bilibili.com/video/BV1Ms411c7mG",
    },
    {
        "title": "【唐迟】考研英语 写作 高分句型",
        "author": "唐迟老师",
        "views": 345000,
        "description": "唐迟老师高分句型课，讲解写作中常用的高级句型和表达。掌握这些句型，作文分数提升一个档次！",
        "url": "https://www.bilibili.com/video/BV1Ns411c7mH",
    },
    {
        "title": "【刘晓艳】考研英语 阅读理解 全题型技巧",
        "author": "刘晓艳老师",
        "views": 423000,
        "description": "刘晓艳老师阅读理解全题型技巧课，涵盖主旨题、细节题、推断题、态度题等所有题型。",
        "url": "https://www.bilibili.com/video/BV1Os411c7mI",
    },
    {
        "title": "【何凯文】考研英语 冲刺阶段复习规划",
        "author": "何凯文老师",
        "views": 356000,
        "description": "何凯文老师冲刺阶段英语复习规划，最后阶段怎么安排最高效。考前必看！",
        "url": "https://www.bilibili.com/video/BV1Ps411c7mJ",
    },
    {
        "title": "【唐迟】考研英语 翻译真题讲解",
        "author": "唐迟老师",
        "views": 234000,
        "description": "唐迟老师翻译真题讲解，分析翻译评分标准和得分技巧。翻译要拿高分，关键是准确理解原文！",
        "url": "https://www.bilibili.com/video/BV1Qs411c7mK",
    },
    {
        "title": "【刘晓艳】考研英语 作文预测 2024",
        "author": "刘晓艳老师",
        "views": 567000,
        "description": "刘晓艳老师2024考研英语作文预测，热点话题和范文。考前背一背，心里有底！",
        "url": "https://www.bilibili.com/video/BV1Rs411c7mL",
    },
    {
        "title": "【何凯文】考研英语 阅读真题 2022年精讲",
        "author": "何凯文老师",
        "views": 412000,
        "description": "何凯文老师精讲2022年考研英语阅读真题，逐句翻译，逐题分析。真题至少要做3遍！",
        "url": "https://www.bilibili.com/video/BV1Ss411c7mM",
    },
    {
        "title": "【唐迟】考研英语 写作 模板定制",
        "author": "唐迟老师",
        "views": 389000,
        "description": "唐迟老师写作模板定制课，教你如何根据自己的水平定制专属模板。模板不是死记硬背，要学会灵活运用！",
        "url": "https://www.bilibili.com/video/BV1Ts411c7mN",
    },
    {
        "title": "【刘晓艳】考研英语 暑假英语复习规划",
        "author": "刘晓艳老师",
        "views": 323000,
        "description": "刘晓艳老师暑假英语复习规划，暑假怎么安排最高效。暑假是英语提分的黄金期！",
        "url": "https://www.bilibili.com/video/BV1Us411c7mO",
    },
    {
        "title": "【何凯文】考研英语 写作 大作文三段式模板",
        "author": "何凯文老师",
        "views": 456000,
        "description": "何凯文老师大作文三段式模板课，描述图画+分析原因+总结建议。万能模板，考场上直接套用！",
        "url": "https://www.bilibili.com/video/BV1Vs411c7mP",
    },
    {
        "title": "【唐迟】考研英语 单词速记 词根词缀",
        "author": "唐迟老师",
        "views": 289000,
        "description": "唐迟老师词根词缀速记单词，掌握100个常见词根词缀，推断500+生词含义。高效背单词！",
        "url": "https://www.bilibili.com/video/BV1Ws411c7mQ",
    },
    {
        "title": "【刘晓艳】考研英语 翻译满分技巧",
        "author": "刘晓艳老师",
        "views": 256000,
        "description": "刘晓艳老师翻译满分技巧课，讲解翻译的得分点和常见错误。翻译要拿满分，关键是准确+流畅！",
        "url": "https://www.bilibili.com/video/BV1Xs411c7mR",
    },
    {
        "title": "【何凯文】考研英语 每日一练 阅读理解",
        "author": "何凯文老师",
        "views": 678000,
        "description": "何凯文老师每日一练系列，每天一篇阅读理解练习，积累阅读量。阅读要拿高分，靠的是日积月累！",
        "url": "https://www.bilibili.com/video/BV1Ys411c7mS",
    },
    {
        "title": "【唐迟】考研英语 全年复习规划",
        "author": "唐迟老师",
        "views": 512000,
        "description": "唐迟老师考研英语全年复习规划，从3月到12月，每个阶段怎么安排。跟着规划走，英语稳拿75+！",
        "url": "https://www.bilibili.com/video/BV1Zs411c7mT",
    },

    # === 政治 (30条) ===
    {
        "title": "【徐涛】考研政治 基础班 马克思主义基本原理",
        "author": "徐涛老师",
        "views": 534000,
        "description": "徐涛老师马原基础班，讲解马克思主义基本原理的核心概念。徐涛讲课生动有趣，马原不再枯燥！",
        "url": "https://www.bilibili.com/video/BV1as411c7mU",
    },
    {
        "title": "【肖秀荣】考研政治 1000题讲解 马原部分",
        "author": "肖秀荣教授",
        "views": 423000,
        "description": "肖秀荣1000题马原部分讲解，逐题分析选项对错原因。1000题是考研政治必做题集！",
        "url": "https://www.bilibili.com/video/BV1bs411c7mV",
    },
    {
        "title": "【腿姐】考研政治 答题技巧 大题模板",
        "author": "腿姐陆寓丰",
        "views": 612000,
        "description": "腿姐政治大题答题技巧和模板，教你如何规范答题拿高分。政治大题有套路！",
        "url": "https://www.bilibili.com/video/BV1cs411c7mW",
    },
    {
        "title": "【徐涛】考研政治 毛中特 基础班",
        "author": "徐涛老师",
        "views": 456000,
        "description": "徐涛老师毛中特基础班，系统讲解毛泽东思想和中国特色社会主义理论体系。毛中特是政治分值最大的部分！",
        "url": "https://www.bilibili.com/video/BV1ds411c7mX",
    },
    {
        "title": "【肖秀荣】考研政治 形势与政策 时政热点",
        "author": "肖秀荣教授",
        "views": 567000,
        "description": "肖秀荣老师形势与政策时政热点讲解，涵盖当年重大时政事件。时政是考研政治的必考内容！",
        "url": "https://www.bilibili.com/video/BV1es411c7mY",
    },
    {
        "title": "【腿姐】考研政治 选择题技巧 多选题攻略",
        "author": "腿姐陆寓丰",
        "views": 489000,
        "description": "腿姐选择题技巧课，重点讲解多选题解题方法。多选题是政治拉分的关键！",
        "url": "https://www.bilibili.com/video/BV1fs411c7mZ",
    },
    {
        "title": "【徐涛】考研政治 史纲 基础班",
        "author": "徐涛老师",
        "views": 378000,
        "description": "徐涛老师史纲基础班，讲解中国近现代史纲要的核心内容。史纲时间线清晰，容易拿分！",
        "url": "https://www.bilibili.com/video/BV1gs411c7mA",
    },
    {
        "title": "【肖秀荣】考研政治 肖八选择题精讲",
        "author": "肖秀荣教授",
        "views": 789000,
        "description": "肖秀荣肖八选择题精讲，逐题分析考点和解题思路。肖八是冲刺阶段最重要的资料！",
        "url": "https://www.bilibili.com/video/BV1hs411c7mB",
    },
    {
        "title": "【腿姐】考研政治 思修法基 技巧班",
        "author": "腿姐陆寓丰",
        "views": 345000,
        "description": "腿姐思修法基技巧班，讲解思想道德修养与法律基础的答题技巧。思修法基相对简单，要拿高分！",
        "url": "https://www.bilibili.com/video/BV1is411c7mC",
    },
    {
        "title": "【徐涛】考研政治 政治经济学",
        "author": "徐涛老师",
        "views": 289000,
        "description": "徐涛老师政治经济学讲解，这部分是马原的重点和难点。徐涛的讲解让政经变得通俗易懂！",
        "url": "https://www.bilibili.com/video/BV1js411c7mD",
    },
    {
        "title": "【肖秀荣】考研政治 肖四大题背诵",
        "author": "肖秀荣教授",
        "views": 923000,
        "description": "肖秀荣肖四大题背诵版，考前必背！肖四押题准确率极高，大题背肖四就够了！",
        "url": "https://www.bilibili.com/video/BV1ks411c7mE",
    },
    {
        "title": "【腿姐】考研政治 答题模板 马原大题",
        "author": "腿姐陆寓丰",
        "views": 389000,
        "description": "腿姐马原大题答题模板，教你如何规范答题拿高分。马原大题有固定套路！",
        "url": "https://www.bilibili.com/video/BV1ls411c7mF",
    },
    {
        "title": "【徐涛】考研政治 强化班 毛中特重点章节",
        "author": "徐涛老师",
        "views": 412000,
        "description": "徐涛老师毛中特强化班，重点讲解高频考点章节。强化阶段要抓住重点！",
        "url": "https://www.bilibili.com/video/BV1ms411c7mG",
    },
    {
        "title": "【肖秀荣】考研政治 1000题 毛中特部分",
        "author": "肖秀荣教授",
        "views": 356000,
        "description": "肖秀荣1000题毛中特部分讲解，逐题分析。毛中特分值最大，要重点掌握！",
        "url": "https://www.bilibili.com/video/BV1ns411c7mH",
    },
    {
        "title": "【腿姐】考研政治 冲刺班 最后30天规划",
        "author": "腿姐陆寓丰",
        "views": 534000,
        "description": "腿姐最后30天冲刺规划，政治怎么安排最高效。考前必看！",
        "url": "https://www.bilibili.com/video/BV1os411c7mI",
    },
    {
        "title": "【徐涛】考研政治 思修法基 基础班",
        "author": "徐涛老师",
        "views": 267000,
        "description": "徐涛老师思修法基基础班，讲解思想道德修养与法律基础的核心内容。这部分相对简单，要拿高分！",
        "url": "https://www.bilibili.com/video/BV1ps411c7mJ",
    },
    {
        "title": "【肖秀荣】考研政治 肖八大题 答题思路",
        "author": "肖秀荣教授",
        "views": 445000,
        "description": "肖秀荣肖八大题答题思路讲解，教你如何分析材料、组织答案。答题有方法！",
        "url": "https://www.bilibili.com/video/BV1qs411c7mK",
    },
    {
        "title": "【腿姐】考研政治 真题讲解 选择题",
        "author": "腿姐陆寓丰",
        "views": 323000,
        "description": "腿姐政治真题选择题讲解，分析命题规律和解题技巧。真题是最好的复习资料！",
        "url": "https://www.bilibili.com/video/BV1rs411c7mL",
    },
    {
        "title": "【徐涛】考研政治 基础班全套合集",
        "author": "徐涛老师",
        "views": 856000,
        "description": "徐涛老师政治基础班全套合集，从马原到时政，系统全面。政治跟徐涛，轻松拿高分！",
        "url": "https://www.bilibili.com/video/BV1ss411c7mM",
    },
    {
        "title": "【肖秀荣】考研政治 1000题讲解 史纲部分",
        "author": "肖秀荣教授",
        "views": 312000,
        "description": "肖秀荣1000题史纲部分讲解，逐题分析。史纲时间线清晰，容易拿分！",
        "url": "https://www.bilibili.com/video/BV1ts411c7mN",
    },
    {
        "title": "【腿姐】考研政治 时政热点 最新整理",
        "author": "腿姐陆寓丰",
        "views": 478000,
        "description": "腿姐时政热点整理，涵盖当年重大时政事件和考点。时政每年都要更新，要关注最新内容！",
        "url": "https://www.bilibili.com/video/BV1us411c7mO",
    },
    {
        "title": "【徐涛】考研政治 马原 重难点讲解",
        "author": "徐涛老师",
        "views": 345000,
        "description": "徐涛老师马原重难点讲解，深入分析马克思主义基本原理的核心考点。马原是政治最难的部分！",
        "url": "https://www.bilibili.com/video/BV1vs411c7mP",
    },
    {
        "title": "【肖秀荣】考研政治 肖四肖八 使用方法",
        "author": "肖秀荣教授",
        "views": 623000,
        "description": "肖秀荣老师讲解肖四肖八的正确使用方法。肖四背大题，肖八做选择题，这是考研政治的黄金搭配！",
        "url": "https://www.bilibili.com/video/BV1ws411c7mQ",
    },
    {
        "title": "【腿姐】考研政治 选择题 常见陷阱",
        "author": "腿姐陆寓丰",
        "views": 389000,
        "description": "腿姐选择题常见陷阱分析，帮助避免常见错误。知己知彼，百战不殆！",
        "url": "https://www.bilibili.com/video/BV1xs411c7mR",
    },
    {
        "title": "【徐涛】考研政治 暑假规划 政治怎么学",
        "author": "徐涛老师",
        "views": 356000,
        "description": "徐涛老师暑假政治学习规划，暑假怎么安排政治复习。政治不用太早，暑假开始正好！",
        "url": "https://www.bilibili.com/video/BV1ys411c7mS",
    },
    {
        "title": "【肖秀荣】考研政治 选择题速成法",
        "author": "肖秀荣教授",
        "views": 423000,
        "description": "肖秀荣选择题速成法，短时间内快速提高选择题分数。选择题是拉开差距的关键！",
        "url": "https://www.bilibili.com/video/BV1zs411c7mT",
    },
    {
        "title": "【腿姐】考研政治 大题答题规范",
        "author": "腿姐陆寓丰",
        "views": 298000,
        "description": "腿姐大题答题规范课，教你如何规范答题拿高分。答题格式和语言组织很重要！",
        "url": "https://www.bilibili.com/video/BV1As411c7mU",
    },
    {
        "title": "【徐涛】考研政治 全年复习规划",
        "author": "徐涛老师",
        "views": 512000,
        "description": "徐涛老师考研政治全年复习规划，从7月到12月，每个阶段怎么安排。政治不用太早，但要高效！",
        "url": "https://www.bilibili.com/video/BV1Bs411c7mV",
    },
    {
        "title": "【肖秀荣】考研政治 2024年押题预测",
        "author": "肖秀荣教授",
        "views": 856000,
        "description": "肖秀荣老师2024年考研政治押题预测，重点热点全覆盖。考前背一背，心里有底！",
        "url": "https://www.bilibili.com/video/BV1Cs411c7mW",
    },

    # === 专业课 (30条) ===
    {
        "title": "【王道】408计算机考研 数据结构 线性表",
        "author": "考研名师课堂",
        "views": 345000,
        "description": "王道408数据结构线性表章节，讲解数组、链表、栈、队列等数据结构。408是计算机考研的核心科目！",
        "url": "https://www.bilibili.com/video/BV1Ds411c7mX",
    },
    {
        "title": "【王道】408计算机考研 计算机组成原理",
        "author": "考研名师课堂",
        "views": 289000,
        "description": "王道408计算机组成原理章节，讲解CPU、存储器、总线等核心概念。计组是408的重点！",
        "url": "https://www.bilibili.com/video/BV1Es411c7mY",
    },
    {
        "title": "【王道】408计算机考研 操作系统 进程管理",
        "author": "考研名师课堂",
        "views": 267000,
        "description": "王道408操作系统进程管理章节，讲解进程、线程、同步、死锁等概念。操作系统是408的重要组成部分！",
        "url": "https://www.bilibili.com/video/BV1Fs411c7mZ",
    },
    {
        "title": "【王道】408计算机考研 计算机网络",
        "author": "考研名师课堂",
        "views": 234000,
        "description": "王道408计算机网络章节，讲解OSI七层模型、TCP/IP协议等。计网是408的最后一部分！",
        "url": "https://www.bilibili.com/video/BV1Gs411c7mA",
    },
    {
        "title": "【408真题】2024年计算机考研408真题讲解",
        "author": "考研名师课堂",
        "views": 456000,
        "description": "2024年考研408真题讲解，逐题分析解题思路和考点。真题是最好的复习资料！",
        "url": "https://www.bilibili.com/video/BV1Hs411c7mB",
    },
    {
        "title": "【数据结构】考研必考 树与二叉树",
        "author": "考研名师课堂",
        "views": 312000,
        "description": "数据结构核心章节：树与二叉树。讲解二叉树的遍历、平衡树、哈夫曼树等。树是数据结构的重点！",
        "url": "https://www.bilibili.com/video/BV1Is411c7mC",
    },
    {
        "title": "【数据结构】考研必考 图的遍历与最短路径",
        "author": "考研名师课堂",
        "views": 278000,
        "description": "数据结构图的章节，讲解图的遍历（BFS/DFS）和最短路径算法（Dijkstra/Floyd）。图是数据结构的难点！",
        "url": "https://www.bilibili.com/video/BV1Js411c7mD",
    },
    {
        "title": "【计组】考研重点 指令系统与CPU",
        "author": "考研名师课堂",
        "views": 245000,
        "description": "计算机组成原理核心章节：指令系统与CPU。讲解指令格式、寻址方式、CPU设计等。这部分是计组的重中之重！",
        "url": "https://www.bilibili.com/video/BV1Ks411c7mE",
    },
    {
        "title": "【计组】考研重点 存储系统与Cache",
        "author": "考研名师课堂",
        "views": 223000,
        "description": "计算机组成原理存储系统章节，讲解主存、Cache、虚拟存储器等。存储系统是计组的高频考点！",
        "url": "https://www.bilibili.com/video/BV1Ls411c7mF",
    },
    {
        "title": "【操作系统】考研重点 内存管理",
        "author": "考研名师课堂",
        "views": 256000,
        "description": "操作系统内存管理章节，讲解页式存储、段式存储、虚拟内存等。内存管理是操作系统的重点！",
        "url": "https://www.bilibili.com/video/BV1Ms411c7mG",
    },
    {
        "title": "【操作系统】考研重点 文件系统",
        "author": "考研名师课堂",
        "views": 189000,
        "description": "操作系统文件系统章节，讲解文件结构、目录结构、磁盘调度等。文件系统是操作系统的常考内容！",
        "url": "https://www.bilibili.com/video/BV1Ns411c7mH",
    },
    {
        "title": "【计算机网络】考研重点 TCP/IP协议",
        "author": "考研名师课堂",
        "views": 234000,
        "description": "计算机网络核心章节：TCP/IP协议。讲解TCP三次握手、四次挥手、拥塞控制等。TCP是计网的重中之重！",
        "url": "https://www.bilibili.com/video/BV1Os411c7mI",
    },
    {
        "title": "【计算机网络】考研重点 应用层",
        "author": "考研名师课堂",
        "views": 178000,
        "description": "计算机网络应用层章节，讲解HTTP、FTP、SMTP等协议。应用层是计网的常考内容！",
        "url": "https://www.bilibili.com/video/BV1Ps411c7mJ",
    },
    {
        "title": "【408冲刺】最后30天 408复习规划",
        "author": "考研名师课堂",
        "views": 389000,
        "description": "408最后30天冲刺规划，如何高效复习四门课。考前必看！",
        "url": "https://www.bilibili.com/video/BV1Qs411c7mK",
    },
    {
        "title": "【数据结构】考研算法题 手写代码技巧",
        "author": "考研名师课堂",
        "views": 298000,
        "description": "数据结构算法题手写代码技巧，教你如何在考场上快速写出正确的代码。算法题是408的拉分项！",
        "url": "https://www.bilibili.com/video/BV1Rs411c7mL",
    },
    {
        "title": "【计组】考研真题讲解 2024年",
        "author": "考研名师课堂",
        "views": 267000,
        "description": "2024年408计组真题讲解，分析命题规律和解题思路。真题是最好的复习资料！",
        "url": "https://www.bilibili.com/video/BV1Ss411c7mM",
    },
    {
        "title": "【操作系统】考研真题讲解 2024年",
        "author": "考研名师课堂",
        "views": 245000,
        "description": "2024年408操作系统真题讲解，分析命题趋势和解题方法。",
        "url": "https://www.bilibili.com/video/BV1Ts411c7mN",
    },
    {
        "title": "【计算机网络】考研真题讲解 2024年",
        "author": "考研名师课堂",
        "views": 212000,
        "description": "2024年408计网真题讲解，分析解题思路和考点分布。",
        "url": "https://www.bilibili.com/video/BV1Us411c7mO",
    },
    {
        "title": "【408复习】四门课复习顺序与时间安排",
        "author": "考研名师课堂",
        "views": 423000,
        "description": "408四门课复习顺序：数据结构→计组→操作系统→计网。时间安排和复习方法全面讲解。",
        "url": "https://www.bilibili.com/video/BV1Vs411c7mP",
    },
    {
        "title": "【数据结构】考研排序算法专题",
        "author": "考研名师课堂",
        "views": 256000,
        "description": "数据结构排序算法专题，讲解各种排序算法的时间复杂度、空间复杂度和适用场景。排序是必考内容！",
        "url": "https://www.bilibili.com/video/BV1Ws411c7mQ",
    },
    {
        "title": "【数据结构】考研查找算法专题",
        "author": "考研名师课堂",
        "views": 223000,
        "description": "数据结构查找算法专题，讲解顺序查找、二分查找、哈希查找、B树查找等。查找是数据结构的重点！",
        "url": "https://www.bilibili.com/video/BV1Xs411c7mR",
    },
    {
        "title": "【计组】考研总线与I/O系统",
        "author": "考研名师课堂",
        "views": 189000,
        "description": "计算机组成原理总线与I/O系统章节，讲解总线结构、I/O方式等。这部分是计组的基础内容！",
        "url": "https://www.bilibili.com/video/BV1Ys411c7mS",
    },
    {
        "title": "【操作系统】考研死锁与线程同步",
        "author": "考研名师课堂",
        "views": 234000,
        "description": "操作系统死锁与线程同步章节，讲解死锁的条件、预防、避免，以及信号量、管程等同步机制。这是操作系统的难点！",
        "url": "https://www.bilibili.com/video/BV1Zs411c7mT",
    },
    {
        "title": "【计算机网络】考研物理层与数据链路层",
        "author": "考研名师课堂",
        "views": 178000,
        "description": "计算机网络物理层与数据链路层章节，讲解编码、调制、差错控制等基础概念。计网的基础！",
        "url": "https://www.bilibili.com/video/BV1as411c7mU",
    },
    {
        "title": "【408模拟】模拟考试与成绩分析",
        "author": "考研名师课堂",
        "views": 312000,
        "description": "408模拟考试讲解，分析常见错误和薄弱环节。模拟考试是检验复习效果的最好方法！",
        "url": "https://www.bilibili.com/video/BV1bs411c7mV",
    },
    {
        "title": "【408资料】王道考研四本书使用指南",
        "author": "考研名师课堂",
        "views": 356000,
        "description": "王道考研四本书使用指南，如何高效利用王道系列资料复习408。王道是408复习的核心资料！",
        "url": "https://www.bilibili.com/video/BV1cs411c7mW",
    },
    {
        "title": "【408高频考点】四门课核心知识点汇总",
        "author": "考研名师课堂",
        "views": 445000,
        "description": "408四门课核心知识点汇总，快速回顾高频考点。考前必看！",
        "url": "https://www.bilibili.com/video/BV1ds411c7mX",
    },
    {
        "title": "【408避坑】常见错误与易混淆知识点",
        "author": "考研名师课堂",
        "views": 289000,
        "description": "408常见错误与易混淆知识点总结，帮助避免常见陷阱。知己知彼，百战不殆！",
        "url": "https://www.bilibili.com/video/BV1es411c7mY",
    },
    {
        "title": "【408经验】上岸学长分享 408复习经验",
        "author": "上岸学长学姐",
        "views": 378000,
        "description": "上岸学长分享408复习经验，包括时间安排、资料选择、刷题策略等。经验分享比任何规划都有用！",
        "url": "https://www.bilibili.com/video/BV1fs411c7mZ",
    },

    # === 复试 (25条) ===
    {
        "title": "【考研复试】复试面试自我介绍模板 中英文",
        "author": "考研名师课堂",
        "views": 534000,
        "description": "复试面试自我介绍模板，中英文各准备一份，控制在2-3分钟。核心：简洁、有重点、展示学术热情！",
        "url": "https://www.bilibili.com/video/BV1gs411c7mA",
    },
    {
        "title": "【考研复试】英语口语高频问题+回答模板",
        "author": "考研名师课堂",
        "views": 456000,
        "description": "复试英语口语高频问题和回答模板，包括Self-introduction、Why this major等。流利最重要！",
        "url": "https://www.bilibili.com/video/BV1hs411c7mB",
    },
    {
        "title": "【考研复试】专业课面试常见问题汇总",
        "author": "考研名师课堂",
        "views": 389000,
        "description": "复试专业课面试常见问题汇总，包括基础概念、学科前沿、研究方向等。提前准备，胸有成竹！",
        "url": "https://www.bilibili.com/video/BV1is411c7mC",
    },
    {
        "title": "【考研复试】如何联系导师？邮件模板",
        "author": "考研名师课堂",
        "views": 423000,
        "description": "复试前联系导师的方法和邮件模板，教你如何给导师发邮件。邮件要专业简洁！",
        "url": "https://www.bilibili.com/video/BV1js411c7mD",
    },
    {
        "title": "【考研复试】复试材料准备清单",
        "author": "考研名师课堂",
        "views": 312000,
        "description": "复试材料准备清单，包括身份证、成绩单、简历、获奖证书等。材料要提前准备好！",
        "url": "https://www.bilibili.com/video/BV1ks411c7mE",
    },
    {
        "title": "【考研复试】复试面试礼仪与注意事项",
        "author": "考研名师课堂",
        "views": 345000,
        "description": "复试面试礼仪和注意事项，包括着装、进门、坐姿、眼神等。细节体现素养！",
        "url": "https://www.bilibili.com/video/BV1ls411c7mF",
    },
    {
        "title": "【考研复试】复试笔试怎么准备？",
        "author": "考研名师课堂",
        "views": 267000,
        "description": "复试笔试准备方法，如何找真题、复习重点等。复试笔试也很重要，不要只准备面试！",
        "url": "https://www.bilibili.com/video/BV1ms411c7mG",
    },
    {
        "title": "【考研复试】综合面试常见问题+回答技巧",
        "author": "考研名师课堂",
        "views": 378000,
        "description": "综合面试常见问题和回答技巧，包括为什么选这个学校、优缺点、未来规划等。提前准备！",
        "url": "https://www.bilibili.com/video/BV1ns411c7mH",
    },
    {
        "title": "【考研复试】复试被刷的8大原因",
        "author": "考研名师课堂",
        "views": 489000,
        "description": "复试被刷的8大原因分析，帮助避免常见错误。提前了解，有针对性准备！",
        "url": "https://www.bilibili.com/video/BV1os411c7mI",
    },
    {
        "title": "【考研复试】复试成绩怎么算？各部分占比",
        "author": "考研名师课堂",
        "views": 298000,
        "description": "复试成绩构成和各部分占比分析，帮助了解复试的重要性。复试占比不小，一定要重视！",
        "url": "https://www.bilibili.com/video/BV1ps411c7mJ",
    },
    {
        "title": "【考研复试】复试紧张怎么办？心理调节",
        "author": "考研名师课堂",
        "views": 323000,
        "description": "复试紧张的心理调节方法，帮助缓解面试压力。适度紧张反而能提高表现！",
        "url": "https://www.bilibili.com/video/BV1qs411c7mK",
    },
    {
        "title": "【考研复试】如何展示科研经历？",
        "author": "考研名师课堂",
        "views": 278000,
        "description": "复试中如何展示科研经历，有经历重点介绍，没有经历展示学习能力和思考能力。导师看重的是潜力！",
        "url": "https://www.bilibili.com/video/BV1rs411c7mL",
    },
    {
        "title": "【考研复试】复试时间安排 从出分到录取",
        "author": "考研名师课堂",
        "views": 256000,
        "description": "复试全流程时间安排，从出成绩到录取的完整流程。了解流程，心中有数！",
        "url": "https://www.bilibili.com/video/BV1ss411c7mM",
    },
    {
        "title": "【考研复试】复试中遇到不会的问题怎么办？",
        "author": "考研名师课堂",
        "views": 345000,
        "description": "复试中遇到不会的问题的应对方法，诚实+态度+思考过程比瞎编更好！",
        "url": "https://www.bilibili.com/video/BV1ts411c7mN",
    },
    {
        "title": "【考研复试】复试要不要见导师？怎么见？",
        "author": "考研名师课堂",
        "views": 234000,
        "description": "复试前是否要见导师的建议和方法，提前联系导师有助于调剂成功。",
        "url": "https://www.bilibili.com/video/BV1us411c7mO",
    },
    {
        "title": "【考研复试】调剂复试和一志愿复试区别",
        "author": "考研名师课堂",
        "views": 289000,
        "description": "调剂复试和一志愿复试的区别，帮助有针对性准备。调剂复试准备时间更短，要更高效！",
        "url": "https://www.bilibili.com/video/BV1vs411c7mP",
    },
    {
        "title": "【考研复试】复试模拟面试 实战演练",
        "author": "考研名师课堂",
        "views": 356000,
        "description": "复试模拟面试实战演练，展示真实的面试场景和应对方法。模拟面试是最好的准备方式！",
        "url": "https://www.bilibili.com/video/BV1ws411c7mQ",
    },
    {
        "title": "【考研复试】复试简历怎么写？模板",
        "author": "考研名师课堂",
        "views": 312000,
        "description": "复试简历写作模板，突出教育背景、项目经历、获奖情况等。简历要简洁专业！",
        "url": "https://www.bilibili.com/video/BV1xs411c7mR",
    },
    {
        "title": "【考研复试】复试英语自我介绍范文",
        "author": "考研名师课堂",
        "views": 298000,
        "description": "复试英语自我介绍范文，包括基本信息、本科经历、为什么选这个学校、未来规划。控制在2-3分钟！",
        "url": "https://www.bilibili.com/video/BV1ys411c7mS",
    },
    {
        "title": "【考研复试】复试着装建议",
        "author": "考研名师课堂",
        "views": 189000,
        "description": "复试着装建议，干净整洁即可，不必穿正装。第一印象很重要！",
        "url": "https://www.bilibili.com/video/BV1zs411c7mT",
    },
    {
        "title": "【考研复试】复试常见雷区 避坑指南",
        "author": "考研名师课堂",
        "views": 378000,
        "description": "复试常见雷区和避坑指南，帮助避免面试中的常见错误。知己知彼，百战不殆！",
        "url": "https://www.bilibili.com/video/BV1As411c7mU",
    },
    {
        "title": "【考研复试】复试高频英语问题 Top20",
        "author": "考研名师课堂",
        "views": 345000,
        "description": "复试高频英语问题Top20，涵盖自我介绍、专业问题、生活问题等。提前准备，面试不慌！",
        "url": "https://www.bilibili.com/video/BV1Bs411c7mV",
    },
    {
        "title": "【考研复试】复试导师提问套路分析",
        "author": "考研名师课堂",
        "views": 267000,
        "description": "复试导师提问套路分析，了解导师的提问思路，有针对性准备。知己知彼！",
        "url": "https://www.bilibili.com/video/BV1Cs411c7mW",
    },
    {
        "title": "【考研复试】复试经验分享 上岸学长",
        "author": "上岸学长学姐",
        "views": 412000,
        "description": "上岸学长复试经验分享，包括准备过程、面试经历、心得体会等。经验分享比任何规划都有用！",
        "url": "https://www.bilibili.com/video/BV1Ds411c7mX",
    },
    {
        "title": "【考研复试】复试全流程详解 小白必看",
        "author": "考研名师课堂",
        "views": 323000,
        "description": "复试全流程详解，从报到到录取的完整流程。小白必看！",
        "url": "https://www.bilibili.com/video/BV1Es411c7mY",
    },

    # === 调剂 (20条) ===
    {
        "title": "【考研调剂】调剂系统操作流程详解",
        "author": "考研名师课堂",
        "views": 567000,
        "description": "调剂系统操作流程详解，从登录到录取的完整步骤。调剂小白必看！",
        "url": "https://www.bilibili.com/video/BV1Fs411c7mZ",
    },
    {
        "title": "【考研调剂】调剂信息从哪里找？6个渠道",
        "author": "考研名师课堂",
        "views": 423000,
        "description": "调剂信息6个渠道：研招网、院校官网、考研论坛、QQ群、学长学姐、研招办电话。信息是调剂成功的关键！",
        "url": "https://www.bilibili.com/video/BV1Gs411c7mA",
    },
    {
        "title": "【考研调剂】调剂避坑指南 常见错误",
        "author": "考研名师课堂",
        "views": 389000,
        "description": "调剂常见坑和避坑指南，帮助避免调剂过程中的常见错误。提前了解，少走弯路！",
        "url": "https://www.bilibili.com/video/BV1Hs411c7mB",
    },
    {
        "title": "【考研调剂】B区211调剂推荐",
        "author": "考研名师课堂",
        "views": 456000,
        "description": "B区211调剂推荐，包括广西大学、云南大学、贵州大学、兰州大学等。B区性价比很高！",
        "url": "https://www.bilibili.com/video/BV1Is411c7mC",
    },
    {
        "title": "【考研调剂】调剂被刷了怎么办？出路分析",
        "author": "考研名师课堂",
        "views": 345000,
        "description": "调剂被刷后的出路分析，包括继续等待、二战、就业、出国、考公等。人生不是只有一条路！",
        "url": "https://www.bilibili.com/video/BV1Js411c7mD",
    },
    {
        "title": "【考研调剂】调剂学校怎么选？4个要点",
        "author": "考研名师课堂",
        "views": 289000,
        "description": "调剂选校4个要点：专业对口、学校层次、地理位置、复试时间。合理选择，提高成功率！",
        "url": "https://www.bilibili.com/video/BV1Ks411c7mE",
    },
    {
        "title": "【考研调剂】调剂前准备工作",
        "author": "考研名师课堂",
        "views": 312000,
        "description": "调剂前准备清单：收集信息、准备材料、写邮件模板、准备复试。提前准备才能抢占先机！",
        "url": "https://www.bilibili.com/video/BV1Ls411c7mF",
    },
    {
        "title": "【考研调剂】如何提前联系导师？",
        "author": "考研名师课堂",
        "views": 267000,
        "description": "调剂时如何提前联系导师，邮件怎么写，注意事项有哪些。提前联系有助于调剂成功！",
        "url": "https://www.bilibili.com/video/BV1Ms411c7mG",
    },
    {
        "title": "【考研调剂】调剂到普通一本值不值得？",
        "author": "考研名师课堂",
        "views": 378000,
        "description": "调剂到普通一本的价值分析，关键看研究方向、导师水平和个人努力。先上岸再说！",
        "url": "https://www.bilibili.com/video/BV1Ns411c7mH",
    },
    {
        "title": "【考研调剂】48小时黄金期怎么把握？",
        "author": "考研名师课堂",
        "views": 423000,
        "description": "调剂系统开放后48小时黄金期策略，速度决定一切！提前准备才能抢占先机！",
        "url": "https://www.bilibili.com/video/BV1Os411c7mI",
    },
    {
        "title": "【考研调剂】调剂邮件模板 怎么写？",
        "author": "考研名师课堂",
        "views": 298000,
        "description": "调剂邮件模板和写作技巧，邮件要简洁专业，突出亮点。模板邮件要针对性修改！",
        "url": "https://www.bilibili.com/video/BV1Ps411c7mJ",
    },
    {
        "title": "【考研调剂】一志愿和调剂可以同时准备吗？",
        "author": "考研名师课堂",
        "views": 245000,
        "description": "一志愿复试和调剂是否可以同时准备的建议。一志愿优先，调剂作为备选！",
        "url": "https://www.bilibili.com/video/BV1Qs411c7mK",
    },
    {
        "title": "【考研调剂】调剂到专硕还是学硕？",
        "author": "考研名师课堂",
        "views": 267000,
        "description": "调剂时专硕和学硕的选择建议。调剂时不要挑，先上岸再说！",
        "url": "https://www.bilibili.com/video/BV1Rs411c7mL",
    },
    {
        "title": "【考研调剂】调剂复试和一志愿复试区别",
        "author": "考研名师课堂",
        "views": 234000,
        "description": "调剂复试和一志愿复试的区别，帮助有针对性准备。调剂复试准备时间更短！",
        "url": "https://www.bilibili.com/video/BV1Ss411c7mM",
    },
    {
        "title": "【考研调剂】调剂经验分享 上岸学长",
        "author": "上岸学长学姐",
        "views": 356000,
        "description": "上岸学长调剂经验分享，从985落榜到211录取的全过程。经验分享最有价值！",
        "url": "https://www.bilibili.com/video/BV1Ts411c7mN",
    },
    {
        "title": "【考研调剂】调剂全流程 时间节点",
        "author": "考研名师课堂",
        "views": 289000,
        "description": "调剂全流程和时间节点，从国家线公布到录取的完整流程。了解流程，心中有数！",
        "url": "https://www.bilibili.com/video/BV1Us411c7mO",
    },
    {
        "title": "【考研调剂】调剂信息汇总 持续更新",
        "author": "考研名师课堂",
        "views": 445000,
        "description": "调剂信息汇总，持续更新各院校调剂名额和要求。调剂信息是成功的关键！",
        "url": "https://www.bilibili.com/video/BV1Vs411c7mP",
    },
    {
        "title": "【考研调剂】调剂心态调整",
        "author": "考研名师课堂",
        "views": 223000,
        "description": "调剂期间的心态调整，不要灰心，机会还有很多。保持积极心态！",
        "url": "https://www.bilibili.com/video/BV1Ws411c7mQ",
    },
    {
        "title": "【考研调剂】2024年调剂政策解读",
        "author": "考研名师课堂",
        "views": 345000,
        "description": "2024年考研调剂政策解读，了解最新调剂规则和变化。政策变化可能影响你的调剂策略！",
        "url": "https://www.bilibili.com/video/BV1Xs411c7mR",
    },
    {
        "title": "【考研调剂】调剂到名校的机会在哪？",
        "author": "考研名师课堂",
        "views": 312000,
        "description": "调剂到名校的机会分析，部分名校也有调剂名额。不要放弃任何机会！",
        "url": "https://www.bilibili.com/video/BV1Ys411c7mS",
    },

    # === 择校 (20条) ===
    {
        "title": "【考研择校】2025考研择校5大原则",
        "author": "考研名师课堂",
        "views": 534000,
        "description": "2025考研择校5大原则：评估实力、研究分数线、关注推免比例、考虑地理位置、联系学长学姐。选对学校比努力更重要！",
        "url": "https://www.bilibili.com/video/BV1Zs411c7mT",
    },
    {
        "title": "【考研择校】双非逆袭985 择校攻略",
        "author": "上岸学长学姐",
        "views": 489000,
        "description": "双非逆袭985的择校攻略，如何选择对双非友好的学校。不要被出身限制想象力！",
        "url": "https://www.bilibili.com/video/BV1as411c7mU",
    },
    {
        "title": "【考研择校】专硕还是学硕？怎么选？",
        "author": "考研名师课堂",
        "views": 423000,
        "description": "专硕和学硕的全面对比和选择建议。想读博选学硕，想就业选专硕！",
        "url": "https://www.bilibili.com/video/BV1bs411c7mV",
    },
    {
        "title": "【考研择校】2025考研扩招院校汇总",
        "author": "考研名师课堂",
        "views": 567000,
        "description": "2025年扩招院校汇总，扩招意味着机会！但竞争依然激烈！",
        "url": "https://www.bilibili.com/video/BV1cs411c7mW",
    },
    {
        "title": "【考研择校】择校必查信息清单",
        "author": "考研名师课堂",
        "views": 378000,
        "description": "择校前必查信息清单：分数线、报录比、推免比例、复试政策等。信息不对称会导致高分落榜！",
        "url": "https://www.bilibili.com/video/BV1ds411c7mX",
    },
    {
        "title": "【考研择校】A区vsB区 怎么选？",
        "author": "考研名师课堂",
        "views": 345000,
        "description": "A区和B区的对比分析，B区国家线低10分，竞争相对较小。调剂时B区是很好的选择！",
        "url": "https://www.bilibili.com/video/BV1es411c7mY",
    },
    {
        "title": "【考研择校】跨专业考研怎么选学校？",
        "author": "考研名师课堂",
        "views": 312000,
        "description": "跨专业考研择校建议，选对跨考生友好的学校。跨考不是劣势，很多导师欢迎不同背景的学生！",
        "url": "https://www.bilibili.com/video/BV1fs411c7mZ",
    },
    {
        "title": "【考研择校】考研报名常见错误 避坑指南",
        "author": "考研名师课堂",
        "views": 356000,
        "description": "考研报名常见错误和避坑指南，帮助避免低级错误耽误考试。细节决定成败！",
        "url": "https://www.bilibili.com/video/BV1gs411c7mA",
    },
    {
        "title": "【考研择校】冲稳保三档搭配策略",
        "author": "考研名师课堂",
        "views": 289000,
        "description": "科学择校方法：冲一冲+稳一稳+保一保。不要把所有鸡蛋放在一个篮子里！",
        "url": "https://www.bilibili.com/video/BV1hs411c7mB",
    },
    {
        "title": "【考研择校】研究生院官网必看信息",
        "author": "考研名师课堂",
        "views": 267000,
        "description": "研究生院官网必看信息：招生简章、专业目录、历年分数线、复试方案等。官网是最权威的信息来源！",
        "url": "https://www.bilibili.com/video/BV1is411c7mC",
    },
    {
        "title": "【考研择校】考研vs考公vs出国 怎么选？",
        "author": "考研名师课堂",
        "views": 412000,
        "description": "考研、考公、出国三种选择的分析，帮助做出适合自己的选择。没有标准答案，适合自己的最好！",
        "url": "https://www.bilibili.com/video/BV1js411c7mD",
    },
    {
        "title": "【考研择校】2025国家线预测",
        "author": "考研名师课堂",
        "views": 523000,
        "description": "2025年国家线预测分析，热门专业可能继续上涨。不要只盯着国家线，目标院校复试线才是关键！",
        "url": "https://www.bilibili.com/video/BV1ks411c7mE",
    },
    {
        "title": "【考研择校】报录比在哪里查？",
        "author": "考研名师课堂",
        "views": 245000,
        "description": "报录比查询渠道：院校官网、研招网、中国考研网、考研帮、学长学姐。报录比是择校的重要参考！",
        "url": "https://www.bilibili.com/video/BV1ls411c7mF",
    },
    {
        "title": "【考研择校】保护一志愿的学校推荐",
        "author": "考研名师课堂",
        "views": 456000,
        "description": "保护一志愿的学校推荐，选校时一定要了解目标院校的复试政策。保护一志愿意味着更公平！",
        "url": "https://www.bilibili.com/video/BV1ms411c7mG",
    },
    {
        "title": "【考研择校】参考书目怎么找？",
        "author": "考研名师课堂",
        "views": 223000,
        "description": "参考书目查询方法：院校官网、研招网、学长学姐、考研论坛。参考书目是复习的指南针！",
        "url": "https://www.bilibili.com/video/BV1ns411c7mH",
    },
    {
        "title": "【考研择校】考研二战值不值得？",
        "author": "考研名师课堂",
        "views": 378000,
        "description": "考研二战是否值得的理性分析，取决于目标是否明确、是否有提升空间。给自己设定期限！",
        "url": "https://www.bilibili.com/video/BV1os411c7mI",
    },
    {
        "title": "【考研择校】2025考研时间节点",
        "author": "考研名师课堂",
        "views": 423000,
        "description": "2025考研重要时间节点：预报名、正式报名、考试、出成绩、国家线、复试调剂。时间很紧，赶紧行动！",
        "url": "https://www.bilibili.com/video/BV1ps411c7mJ",
    },
    {
        "title": "【考研择校】考研报名流程详解",
        "author": "考研名师课堂",
        "views": 298000,
        "description": "考研报名流程详解，从预报名到正式报名的完整步骤。报名流程要清楚！",
        "url": "https://www.bilibili.com/video/BV1qs411c7mK",
    },
    {
        "title": "【考研择校】院校选择与职业规划",
        "author": "考研名师课堂",
        "views": 345000,
        "description": "院校选择与职业规划的关系，如何根据职业目标选择学校。择校要考虑未来发展！",
        "url": "https://www.bilibili.com/video/BV1rs411c7mL",
    },
    {
        "title": "【考研择校】2024年各专业国家线汇总",
        "author": "考研名师课堂",
        "views": 489000,
        "description": "2024年各专业国家线汇总，参考国家线了解竞争程度。这只是国家线，目标院校复试线更高！",
        "url": "https://www.bilibili.com/video/BV1ss411c7mM",
    },

    # === 综合/心态 (30条) ===
    {
        "title": "【考研经验】考研全年复习规划 从3月到12月",
        "author": "考研名师课堂",
        "views": 612000,
        "description": "考研全年复习规划，从基础到冲刺的完整安排。跟着规划走，考研不迷路！",
        "url": "https://www.bilibili.com/video/BV1ts411c7mN",
    },
    {
        "title": "【考研经验】考研暑假计划 弯道超车",
        "author": "考研名师课堂",
        "views": 534000,
        "description": "考研暑假计划，暑假是弯道超车的关键期！不要回家，保持学习节奏！",
        "url": "https://www.bilibili.com/video/BV1us411c7mO",
    },
    {
        "title": "【考研经验】考研最后30天冲刺规划",
        "author": "考研名师课堂",
        "views": 567000,
        "description": "考研最后30天冲刺规划，如何安排最高效。考前必看！",
        "url": "https://www.bilibili.com/video/BV1vs411c7mP",
    },
    {
        "title": "【考研心态】考研焦虑到崩溃怎么办？",
        "author": "考研名师课堂",
        "views": 489000,
        "description": "考研焦虑的心理调节方法，帮助缓解焦虑情绪。保持平稳心态最重要！",
        "url": "https://www.bilibili.com/video/BV1ws411c7mQ",
    },
    {
        "title": "【考研心态】考研坚持不下去了？看看这些话",
        "author": "考研名师课堂",
        "views": 534000,
        "description": "考研坚持不下去时的鼓励和建议。坚持到最后的人就已经赢了一半！",
        "url": "https://www.bilibili.com/video/BV1xs411c7mR",
    },
    {
        "title": "【考研经验】高效学习方法 时间管理",
        "author": "考研名师课堂",
        "views": 456000,
        "description": "高效学习方法和时间管理技巧，帮助提高学习效率。方法对了，效率翻倍！",
        "url": "https://www.bilibili.com/video/BV1ys411c7mS",
    },
    {
        "title": "【考研经验】考研各科时间分配 科学安排",
        "author": "考研名师课堂",
        "views": 423000,
        "description": "考研各科时间分配建议，科学安排各科复习时间。不同科目交替学习！",
        "url": "https://www.bilibili.com/video/BV1zs411c7mT",
    },
    {
        "title": "【考研心态】考研失败了怎么办？人生不只有考研",
        "author": "考研名师课堂",
        "views": 589000,
        "description": "考研失败后的出路分析，人生是旷野不是轨道。不要被一次失败定义！",
        "url": "https://www.bilibili.com/video/BV1As411c7mU",
    },
    {
        "title": "【考研经验】考研学习场所选择",
        "author": "考研名师课堂",
        "views": 345000,
        "description": "考研学习场所对比和选择建议，找到最适合自己的学习环境。效率最重要！",
        "url": "https://www.bilibili.com/video/BV1Bs411c7mV",
    },
    {
        "title": "【考研经验】考研资料怎么选？避坑指南",
        "author": "考研名师课堂",
        "views": 389000,
        "description": "考研资料选择避坑指南，不要买太多资料，选一套吃透比看十套强！",
        "url": "https://www.bilibili.com/video/BV1Cs411c7mW",
    },
    {
        "title": "【考研心态】考研期间如何保持身体健康？",
        "author": "考研名师课堂",
        "views": 312000,
        "description": "考研期间身体健康管理，保证睡眠、运动、饮食。身体垮了，复习计划全泡汤！",
        "url": "https://www.bilibili.com/video/BV1Ds411c7mX",
    },
    {
        "title": "【考研经验】考研期间如何处理焦虑情绪？",
        "author": "考研名师课堂",
        "views": 423000,
        "description": "考研焦虑情绪的处理方法，识别焦虑来源，制定详细计划。焦虑是正常的，关键是不要被焦虑控制！",
        "url": "https://www.bilibili.com/video/BV1Es411c7mY",
    },
    {
        "title": "【考研经验】考研期间要不要找研友？",
        "author": "考研名师课堂",
        "views": 345000,
        "description": "考研期间是否找研友的利弊分析。找一个目标明确、心态稳定的研友，但不要过度依赖！",
        "url": "https://www.bilibili.com/video/BV1Fs411c7mZ",
    },
    {
        "title": "【考研心态】考研人的真实一天",
        "author": "考研名师课堂",
        "views": 512000,
        "description": "考研人的真实一天，枯燥但充实。致敬每一个努力的考研人！",
        "url": "https://www.bilibili.com/video/BV1Gs411c7mA",
    },
    {
        "title": "【考研经验】考研期间如何保持学习动力？",
        "author": "考研名师课堂",
        "views": 389000,
        "description": "保持学习动力的方法，把大目标分解成小目标，每完成一个小目标就奖励自己。动力来自内心！",
        "url": "https://www.bilibili.com/video/BV1Hs411c7mB",
    },
    {
        "title": "【考研心态】考研期间如何应对自我怀疑？",
        "author": "考研名师课堂",
        "views": 412000,
        "description": "应对自我怀疑的方法，把注意力放在进步上，而不是差距上。你已经很努力了，相信自己！",
        "url": "https://www.bilibili.com/video/BV1Is411c7mC",
    },
    {
        "title": "【考研经验】考研结束后如何调整心态？",
        "author": "考研名师课堂",
        "views": 356000,
        "description": "考后心态调整，考完先好好休息，不要反复对答案。无论结果如何，你已经尽力了！",
        "url": "https://www.bilibili.com/video/BV1Js411c7mD",
    },
    {
        "title": "【考研经验】考研期间如何利用碎片时间？",
        "author": "考研名师课堂",
        "views": 323000,
        "description": "碎片时间利用方法，通勤听网课、排队刷题、睡前回顾。碎片时间加起来至少1-2小时！",
        "url": "https://www.bilibili.com/video/BV1Ks411c7mE",
    },
    {
        "title": "【考研经验】考研期间手机怎么管？",
        "author": "考研名师课堂",
        "views": 378000,
        "description": "手机管理方法，学习时把手机锁起来，用Forest种树APP。手机是考研最大的敌人！",
        "url": "https://www.bilibili.com/video/BV1Ls411c7mF",
    },
    {
        "title": "【考研经验】考研期间如何保持社交？",
        "author": "考研名师课堂",
        "views": 289000,
        "description": "考研期间社交平衡，和家人保持联系，每周和朋友聚一次。适度社交有助于心理健康！",
        "url": "https://www.bilibili.com/video/BV1Ms411c7mG",
    },
    {
        "title": "【考研经验】考研人的真实一天 泪目版",
        "author": "考研名师课堂",
        "views": 567000,
        "description": "考研人真实一天的详细记录，从早到晚的学习生活。致敬每一个努力的考研人！",
        "url": "https://www.bilibili.com/video/BV1Ns411c7mH",
    },
    {
        "title": "【考研经验】考研辅导班值不值得报？",
        "author": "考研名师课堂",
        "views": 345000,
        "description": "考研辅导班分析，辅导班只是辅助，关键还是自己的努力！网课性价比更高！",
        "url": "https://www.bilibili.com/video/BV1Os411c7mI",
    },
    {
        "title": "【考研心态】考研期间家人期望带来的压力",
        "author": "考研名师课堂",
        "views": 312000,
        "description": "处理家人期望带来的压力，和家人好好沟通，压力来自自己，调整心态最重要！",
        "url": "https://www.bilibili.com/video/BV1Ps411c7mJ",
    },
    {
        "title": "【考研经验】考研和实习怎么平衡？",
        "author": "考研名师课堂",
        "views": 298000,
        "description": "考研和实习平衡的建议，明确目标，不要两边都想要。切忌摇摆不定！",
        "url": "https://www.bilibili.com/video/BV1Qs411c7mK",
    },
    {
        "title": "【考研经验】考研期间如何处理室友关系？",
        "author": "考研名师课堂",
        "views": 278000,
        "description": "考研期间室友关系处理，尽量去图书馆学习，不要让任何人影响你的复习！",
        "url": "https://www.bilibili.com/video/BV1Rs411c7mL",
    },
    {
        "title": "【考研经验】考研英语作文怎么准备？",
        "author": "考研名师课堂",
        "views": 423000,
        "description": "考研英语作文准备方法，模板+练习。作文是提分最快的部分！",
        "url": "https://www.bilibili.com/video/BV1Ss411c7mM",
    },
    {
        "title": "【考研经验】考研政治怎么学？全年规划",
        "author": "考研名师课堂",
        "views": 389000,
        "description": "考研政治全年学习规划，从7月到12月的安排。政治不用太早，但要高效！",
        "url": "https://www.bilibili.com/video/BV1Ts411c7mN",
    },
    {
        "title": "【考研经验】考研期间恋爱影响学习吗？",
        "author": "考研名师课堂",
        "views": 345000,
        "description": "考研期间恋爱的影响分析，考研是人生重要阶段，不要因为感情影响前途！",
        "url": "https://www.bilibili.com/video/BV1Us411c7mO",
    },
    {
        "title": "【考研经验】考研vs直接就业 过来人怎么说",
        "author": "上岸学长学姐",
        "views": 456000,
        "description": "过来人分享考研和就业的选择经验，想清楚自己的职业目标再决定。适合自己的才是最好的！",
        "url": "https://www.bilibili.com/video/BV1Vs411c7mP",
    },
    {
        "title": "【考研经验】考研内卷越来越严重？如何破局？",
        "author": "考研名师课堂",
        "views": 423000,
        "description": "考研内卷破局方法，尽早确定目标、提高效率、信息收集很关键。专注自身提升！",
        "url": "https://www.bilibili.com/video/BV1Ws411c7mQ",
    },
]


def generate_bilibili_videos():
    """生成B站考研视频数据。"""
    videos = []
    for v_data in VIDEOS:
        video = {
            "title": v_data["title"],
            "author": v_data["author"],
            "views": v_data["views"] + random.randint(-5000, 5000),
            "description": v_data["description"],
            "source": "bilibili",
            "url": v_data["url"],
            "tags": extract_tags_from_title(v_data["title"]),
        }
        videos.append(video)
    random.shuffle(videos)
    return videos


def extract_tags_from_title(title: str) -> list:
    """从标题中提取标签。"""
    tags = []
    tag_map = {
        "数学": "数学", "高数": "数学", "线性代数": "线代",
        "概率论": "概率论", "英语": "英语", "阅读": "阅读",
        "作文": "作文", "翻译": "翻译", "政治": "政治",
        "马原": "马原", "毛中特": "毛中特", "肖": "肖秀荣",
        "徐涛": "徐涛", "腿姐": "腿姐", "408": "408",
        "数据结构": "数据结构", "计组": "计组", "操作系统": "操作系统",
        "计算机网络": "计网", "复试": "复试", "面试": "面试",
        "调剂": "调剂", "择校": "择校", "经验": "经验",
        "心态": "心态", "规划": "规划", "冲刺": "冲刺",
        "真题": "真题", "张宇": "张宇", "汤家凤": "汤家凤",
        "李永乐": "李永乐", "何凯文": "何凯文", "刘晓艳": "刘晓艳",
        "唐迟": "唐迟", "王道": "王道", "上岸": "上岸",
    }
    for kw, tag in tag_map.items():
        if kw in title:
            tags.append(tag)
    return tags[:5] if tags else ["考研"]


def main():
    print("=" * 60)
    print("B站考研视频扩展生成器")
    print("=" * 60)

    print("\n1. 生成B站考研视频数据...")
    videos = generate_bilibili_videos()
    print(f"  生成 {len(videos)} 条视频数据")

    print(f"\n2. 保存到 {OUTPUT_FILE}...")
    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        json.dump(videos, f, ensure_ascii=False, indent=2)
    print(f"  保存成功: {len(videos)} 条视频数据")

    # 统计
    total_views = sum(v["views"] for v in videos)
    print(f"\n  总播放量: {total_views:,}")

    tags_count = {}
    for v in videos:
        for tag in v["tags"]:
            tags_count[tag] = tags_count.get(tag, 0) + 1
    print("\n  标签统计 (Top 10):")
    for tag, count in sorted(tags_count.items(), key=lambda x: -x[1])[:10]:
        print(f"    {tag}: {count} 条")

    authors_count = {}
    for v in videos:
        authors_count[v["author"]] = authors_count.get(v["author"], 0) + 1
    print("\n  UP主统计 (Top 10):")
    for author, count in sorted(authors_count.items(), key=lambda x: -x[1])[:10]:
        print(f"    {author}: {count} 条")

    print("\n完成！")


if __name__ == "__main__":
    main()
