"""add missing standalone tables: career test drives / follows / growth snapshots / learning resources / study plans

Revision ID: efc46b02f792
Revises: 0c836ba2d774
Create Date: 2026-08-13 04:50:28.019802+00:00

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models.base  # noqa: F401 — GUID/JSONB 类型引用（与既有迁移一致）


# revision identifiers, used by Alembic.
revision: str = 'efc46b02f792'
down_revision: Union[str, None] = '0c836ba2d774'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('career_test_drives',
    sa.Column('user_id', app.models.base.GUID(), nullable=False),
    sa.Column('path_type', sa.String(length=50), nullable=False),
    sa.Column('target_role', sa.String(length=100), nullable=False),
    sa.Column('experience_content', app.models.base.JSONB(), nullable=False),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('career_test_drives', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_career_test_drives_user_id'), ['user_id'], unique=False)

    op.create_table('follows',
    sa.Column('follower_id', app.models.base.GUID(), nullable=False),
    sa.Column('followee_id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['followee_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('follower_id', 'followee_id', name='uq_follow_pair')
    )
    with op.batch_alter_table('follows', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_follows_followee_id'), ['followee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_follows_follower_id'), ['follower_id'], unique=False)

    op.create_table('growth_snapshots',
    sa.Column('user_id', app.models.base.GUID(), nullable=False),
    sa.Column('period', sa.String(length=20), nullable=False),
    sa.Column('growth_score', sa.Integer(), nullable=False),
    sa.Column('pattern_count', sa.Integer(), nullable=False),
    sa.Column('snapshot', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('growth_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_growth_snapshots_period'), ['period'], unique=False)
        batch_op.create_index(batch_op.f('ix_growth_snapshots_user_id'), ['user_id'], unique=False)

    op.create_table('learning_resources',
    sa.Column('user_id', app.models.base.GUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('subject', sa.String(length=100), nullable=False),
    sa.Column('difficulty', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tags', app.models.base.JSONB(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('is_free', sa.Boolean(), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('learning_resources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_learning_resources_user_id'), ['user_id'], unique=False)

    op.create_table('study_plans',
    sa.Column('user_id', app.models.base.GUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('start_date', sa.String(length=20), nullable=True),
    sa.Column('end_date', sa.String(length=20), nullable=True),
    sa.Column('subjects', app.models.base.JSONB(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('study_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_study_plans_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_study_plans_user_id'))

    op.drop_table('study_plans')
    with op.batch_alter_table('learning_resources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_learning_resources_user_id'))

    op.drop_table('learning_resources')
    with op.batch_alter_table('growth_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_growth_snapshots_user_id'))
        batch_op.drop_index(batch_op.f('ix_growth_snapshots_period'))

    op.drop_table('growth_snapshots')
    with op.batch_alter_table('follows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_follows_follower_id'))
        batch_op.drop_index(batch_op.f('ix_follows_followee_id'))

    op.drop_table('follows')
    with op.batch_alter_table('career_test_drives', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_career_test_drives_user_id'))

    op.drop_table('career_test_drives')
    # ### end Alembic commands ###
