"""align three center user_id to GUID

Revision ID: 0c836ba2d774
Revises: 08444581f70b
Create Date: 2026-08-12 14:49:47.462966+00:00

6 张三中心契约表（t_action / t_action_checkin / t_action_streak /
t_growth_trajectory / t_growth_archive / t_review_record）的
user_id 由 BigInteger 对齐为 GUID()。

理由：全站 User.id 为 GUID、get_current_user 返回 uuid.UUID，BigInteger
契约无法绑定当前用户；属有意偏离系统设计文档的 int 契约（对齐全站 GUID +
token 推断用户）。t_action_weight 无 user_id 不动。

SQLite 下 GUID() 以 CHAR(32) 存储 UUID hex；batch_alter 重建表并保留
UK/Index（render_as_batch 已开启）。
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.models.base


# revision identifiers, used by Alembic.
revision: str = '0c836ba2d774'
down_revision: Union[str, None] = '08444581f70b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_action', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.BIGINT(),
               type_=app.models.base.GUID(),
               existing_nullable=False)

    with op.batch_alter_table('t_action_checkin', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.BIGINT(),
               type_=app.models.base.GUID(),
               existing_nullable=False)

    with op.batch_alter_table('t_action_streak', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.BIGINT(),
               type_=app.models.base.GUID(),
               existing_nullable=False)

    with op.batch_alter_table('t_growth_archive', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.BIGINT(),
               type_=app.models.base.GUID(),
               existing_nullable=False)

    with op.batch_alter_table('t_growth_trajectory', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.BIGINT(),
               type_=app.models.base.GUID(),
               existing_nullable=False)

    with op.batch_alter_table('t_review_record', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.BIGINT(),
               type_=app.models.base.GUID(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_review_record', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=app.models.base.GUID(),
               type_=sa.BIGINT(),
               existing_nullable=False)

    with op.batch_alter_table('t_growth_trajectory', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=app.models.base.GUID(),
               type_=sa.BIGINT(),
               existing_nullable=False)

    with op.batch_alter_table('t_growth_archive', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=app.models.base.GUID(),
               type_=sa.BIGINT(),
               existing_nullable=False)

    with op.batch_alter_table('t_action_streak', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=app.models.base.GUID(),
               type_=sa.BIGINT(),
               existing_nullable=False)

    with op.batch_alter_table('t_action_checkin', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=app.models.base.GUID(),
               type_=sa.BIGINT(),
               existing_nullable=False)

    with op.batch_alter_table('t_action', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=app.models.base.GUID(),
               type_=sa.BIGINT(),
               existing_nullable=False)

    # ### end Alembic commands ###
