"""add phase B tables: failure cases / family dialogue / micro action / path compare

Revision ID: 08444581f70b
Revises: b90c8dd58221
Create Date: 2026-08-12 13:28:54.712087+00:00

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.models.base


# revision identifiers, used by Alembic.
revision: str = '08444581f70b'
down_revision: Union[str, None] = 'b90c8dd58221'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('failure_cases',
    sa.Column('author_role', sa.String(length=50), nullable=False),
    sa.Column('path_type', sa.String(length=50), nullable=False),
    sa.Column('stage', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('story', sa.Text(), nullable=False),
    sa.Column('lessons', app.models.base.JSONB(), nullable=False),
    sa.Column('regrets', app.models.base.JSONB(), nullable=False),
    sa.Column('what_would_i_do', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('helpful_count', sa.Integer(), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('failure_cases', schema=None) as batch_op:
        batch_op.create_index('ix_failure_case_path_status', ['path_type', 'status'], unique=False)
        batch_op.create_index('ix_failure_case_stage', ['stage'], unique=False)
        batch_op.create_index(batch_op.f('ix_failure_cases_author_role'), ['author_role'], unique=False)
        batch_op.create_index(batch_op.f('ix_failure_cases_path_type'), ['path_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_failure_cases_stage'), ['stage'], unique=False)
        batch_op.create_index(batch_op.f('ix_failure_cases_status'), ['status'], unique=False)

    op.create_table('family_dialogue_sessions',
    sa.Column('user_id', app.models.base.GUID(), nullable=False),
    sa.Column('parent_concern', sa.String(length=200), nullable=False),
    sa.Column('user_choice', sa.String(length=200), nullable=False),
    sa.Column('parent_archetype', sa.String(length=50), nullable=True),
    sa.Column('understanding', sa.Text(), nullable=True),
    sa.Column('prepared_arguments', app.models.base.JSONB(), nullable=False),
    sa.Column('talking_tips', app.models.base.JSONB(), nullable=False),
    sa.Column('practice_messages', app.models.base.JSONB(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('family_dialogue_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_family_dialogue_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('micro_action_plans',
    sa.Column('user_id', app.models.base.GUID(), nullable=False),
    sa.Column('target_path', sa.String(length=50), nullable=False),
    sa.Column('target_role', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('self_discovery_report', sa.Text(), nullable=True),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('micro_action_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_micro_action_plans_user_id'), ['user_id'], unique=False)

    op.create_table('path_comparisons',
    sa.Column('user_id', app.models.base.GUID(), nullable=False),
    sa.Column('paths', app.models.base.JSONB(), nullable=False),
    sa.Column('comparison_result', app.models.base.JSONB(), nullable=False),
    sa.Column('user_context', app.models.base.JSONB(), nullable=True),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('path_comparisons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_path_comparisons_user_id'), ['user_id'], unique=False)

    op.create_table('path_conflict_resolutions',
    sa.Column('user_id', app.models.base.GUID(), nullable=False),
    sa.Column('conflict_type', sa.String(length=50), nullable=False),
    sa.Column('assessment_summary', app.models.base.JSONB(), nullable=False),
    sa.Column('current_situation', app.models.base.JSONB(), nullable=False),
    sa.Column('options', app.models.base.JSONB(), nullable=False),
    sa.Column('selected_option', sa.Integer(), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('action_plan', app.models.base.JSONB(), nullable=False),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('path_conflict_resolutions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_path_conflict_resolutions_user_id'), ['user_id'], unique=False)

    op.create_table('micro_action_tasks',
    sa.Column('plan_id', app.models.base.GUID(), nullable=False),
    sa.Column('day_number', sa.Integer(), nullable=False),
    sa.Column('task_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('estimated_minutes', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_response', sa.Text(), nullable=True),
    sa.Column('insight', sa.Text(), nullable=True),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['micro_action_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('micro_action_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_micro_action_tasks_plan_id'), ['plan_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('micro_action_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_micro_action_tasks_plan_id'))

    op.drop_table('micro_action_tasks')
    with op.batch_alter_table('path_conflict_resolutions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_path_conflict_resolutions_user_id'))

    op.drop_table('path_conflict_resolutions')
    with op.batch_alter_table('path_comparisons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_path_comparisons_user_id'))

    op.drop_table('path_comparisons')
    with op.batch_alter_table('micro_action_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_micro_action_plans_user_id'))

    op.drop_table('micro_action_plans')
    with op.batch_alter_table('family_dialogue_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_family_dialogue_sessions_user_id'))

    op.drop_table('family_dialogue_sessions')
    with op.batch_alter_table('failure_cases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_failure_cases_status'))
        batch_op.drop_index(batch_op.f('ix_failure_cases_stage'))
        batch_op.drop_index(batch_op.f('ix_failure_cases_path_type'))
        batch_op.drop_index(batch_op.f('ix_failure_cases_author_role'))
        batch_op.drop_index('ix_failure_case_stage')
        batch_op.drop_index('ix_failure_case_path_status')

    op.drop_table('failure_cases')
    # ### end Alembic commands ###
