/**
 * 命令面板数据源
 *
 * 列出所有可跳转的页面入口,供 Cmd+K 面板搜索/跳转使用。
 * 图标字段存储 lucide-react 图标名 (PascalCase),由 command-palette.tsx 动态映射到组件。
 */

export interface Command {
  id: string;
  title: string;
  /** 分组/分类,例如 "核心" / "决策" / "情报" */
  subtitle?: string;
  href: string;
  /** 搜索关键词,用于增强匹配 */
  keywords?: string[];
  /** lucide-react 图标名 (PascalCase),例如 "LayoutDashboard" */
  icon?: string;
}

/**
 * 全部命令列表。涵盖应用下所有非动态路由页面,按分组组织。
 * 分组顺序即展示顺序。
 */
export const commands: Command[] = [
  // ────────────────────────── 核心 ──────────────────────────
  {
    id: "dashboard",
    title: "我的看板",
    subtitle: "核心",
    href: "/dashboard",
    keywords: ["首页", "主页", "看板", "dashboard", "home"],
    icon: "LayoutDashboard",
  },
  {
    id: "decision-center",
    title: "决策中心",
    subtitle: "核心",
    href: "/decision-center",
    keywords: ["决策", "中心", "decision", "center"],
    icon: "Target",
  },
  {
    id: "intel",
    title: "情报中心",
    subtitle: "核心",
    href: "/intel",
    keywords: ["情报", "intel", "信息"],
    icon: "Search",
  },

  // ────────────────────────── 决策 ──────────────────────────
  {
    id: "decision-lab",
    title: "决策实验室",
    subtitle: "决策",
    href: "/decision-lab",
    keywords: ["决策", "实验", "lab", "decision"],
    icon: "BeakerIcon",
  },
  {
    id: "decisions",
    title: "去向决策",
    subtitle: "决策",
    href: "/decisions",
    keywords: ["去向", "决策", "decisions", "career path"],
    icon: "GitBranch",
  },
  {
    id: "career-simulator",
    title: "职业路径模拟器",
    subtitle: "决策",
    href: "/career-simulator",
    keywords: ["职业", "模拟", "simulator", "路径"],
    icon: "Route",
  },
  {
    id: "war-room",
    title: "作战室",
    subtitle: "决策",
    href: "/war-room",
    keywords: ["作战", "war", "room", "策略"],
    icon: "Swords",
  },

  // ────────────────────────── 情报 ──────────────────────────
  {
    id: "kaoyan",
    title: "考研工具箱",
    subtitle: "情报",
    href: "/kaoyan",
    keywords: ["考研", "kaoyan", "研究生"],
    icon: "BookOpen",
  },
  {
    id: "civil-service",
    title: "考公中心",
    subtitle: "情报",
    href: "/civil-service",
    keywords: ["考公", "公务员", "civil", "service"],
    icon: "Building2",
  },
  {
    id: "employment",
    title: "就业中心",
    subtitle: "情报",
    href: "/employment",
    keywords: ["就业", "工作", "employment", "job"],
    icon: "Briefcase",
  },
  {
    id: "interview",
    title: "面试经验",
    subtitle: "情报",
    href: "/interview",
    keywords: ["面试", "interview", "经验"],
    icon: "MessageSquare",
  },
  {
    id: "interview-result",
    title: "面试结果",
    subtitle: "情报",
    href: "/interview/result",
    keywords: ["面试", "结果", "interview", "result"],
    icon: "MessageSquare",
  },

  // ────────────────────────── 成长 ──────────────────────────
  {
    id: "growth",
    title: "成长中心",
    subtitle: "成长",
    href: "/growth",
    keywords: ["成长", "growth", "中心"],
    icon: "TrendingUp",
  },
  {
    id: "growth-archive",
    title: "成长档案",
    subtitle: "成长",
    href: "/growth/archive",
    keywords: ["成长", "档案", "archive"],
    icon: "TrendingUp",
  },
  {
    id: "skills",
    title: "技能树",
    subtitle: "成长",
    href: "/skills",
    keywords: ["技能", "树", "skills", "skill tree"],
    icon: "Network",
  },
  {
    id: "life-wheel",
    title: "人生平衡轮",
    subtitle: "成长",
    href: "/life-wheel",
    keywords: ["人生", "平衡", "轮", "life", "wheel"],
    icon: "Compass",
  },
  {
    id: "retrospectives",
    title: "阶段复盘",
    subtitle: "成长",
    href: "/retrospectives",
    keywords: ["复盘", "retrospective", "回顾"],
    icon: "Calendar",
  },
  {
    id: "retrospectives-weekly",
    title: "周复盘",
    subtitle: "成长",
    href: "/retrospectives/weekly",
    keywords: ["周", "复盘", "weekly", "retrospective"],
    icon: "Calendar",
  },
  {
    id: "insights",
    title: "成长洞察",
    subtitle: "成长",
    href: "/insights",
    keywords: ["洞察", "insight", "成长"],
    icon: "Lightbulb",
  },
  {
    id: "growth-patterns",
    title: "成长模式",
    subtitle: "成长",
    href: "/growth-patterns",
    keywords: ["模式", "pattern", "成长"],
    icon: "TrendingUp",
  },
  {
    id: "timeline",
    title: "时间线",
    subtitle: "成长",
    href: "/timeline",
    keywords: ["时间", "线", "timeline"],
    icon: "Calendar",
  },

  // ────────────────────────── 规划 ──────────────────────────
  {
    id: "career",
    title: "职业规划",
    subtitle: "规划",
    href: "/career",
    keywords: ["职业", "规划", "career", "plan"],
    icon: "Map",
  },
  {
    id: "plans",
    title: "计划列表",
    subtitle: "规划",
    href: "/plans",
    keywords: ["计划", "列表", "plans"],
    icon: "ClipboardList",
  },
  {
    id: "study-plans",
    title: "学习计划",
    subtitle: "规划",
    href: "/study-plans",
    keywords: ["学习", "计划", "study", "plan"],
    icon: "Swords",
  },
  {
    id: "study-plans-ai-generate",
    title: "AI 生成学习计划",
    subtitle: "规划",
    href: "/study-plans/ai-generate",
    keywords: ["AI", "生成", "学习", "计划", "ai", "generate"],
    icon: "Sparkles",
  },

  // ────────────────────────── AI ───────────────────────────
  {
    id: "ai-butler",
    title: "AI 对话",
    subtitle: "AI",
    href: "/ai-butler",
    keywords: ["AI", "对话", "butler", "助手"],
    icon: "Bot",
  },
  {
    id: "mentors",
    title: "AI 导师团",
    subtitle: "AI",
    href: "/mentors",
    keywords: ["导师", "AI", "mentor"],
    icon: "Brain",
  },
  {
    id: "life-design",
    title: "人生设计引擎",
    subtitle: "AI",
    href: "/life-design",
    keywords: ["人生", "设计", "life", "design"],
    icon: "Sparkles",
  },
  {
    id: "chat",
    title: "聊天",
    subtitle: "AI",
    href: "/chat",
    keywords: ["聊天", "chat", "对话"],
    icon: "MessageSquare",
  },
  {
    id: "onboarding",
    title: "新手引导",
    subtitle: "AI",
    href: "/onboarding",
    keywords: ["新手", "引导", "onboarding", "入门"],
    icon: "Compass",
  },
  {
    id: "assessment",
    title: "能力评估",
    subtitle: "AI",
    href: "/assessment",
    keywords: ["评估", "测试", "assessment", "能力"],
    icon: "Target",
  },

  // ────────────────────────── 社区 ──────────────────────────
  {
    id: "community",
    title: "社区",
    subtitle: "社区",
    href: "/community",
    keywords: ["社区", "community", "讨论"],
    icon: "Users",
  },
  {
    id: "community-result",
    title: "社区搜索结果",
    subtitle: "社区",
    href: "/community/result",
    keywords: ["社区", "结果", "搜索"],
    icon: "Users",
  },
  {
    id: "outcome-report",
    title: "成果汇报",
    subtitle: "社区",
    href: "/outcome-report",
    keywords: ["成果", "汇报", "outcome", "report"],
    icon: "Trophy",
  },
  {
    id: "outcome-report-landing-wall",
    title: "成果展示墙",
    subtitle: "社区",
    href: "/outcome-report/landing-wall",
    keywords: ["成果", "展示", "墙", "landing", "wall"],
    icon: "Trophy",
  },
  {
    id: "explore",
    title: "探索",
    subtitle: "社区",
    href: "/explore",
    keywords: ["探索", "发现", "explore"],
    icon: "Compass",
  },
  {
    id: "explore-result",
    title: "探索结果",
    subtitle: "社区",
    href: "/explore/result",
    keywords: ["探索", "结果", "explore"],
    icon: "Compass",
  },

  // ────────────────────────── 知识 ──────────────────────────
  {
    id: "knowledge",
    title: "知识库",
    subtitle: "知识",
    href: "/knowledge",
    keywords: ["知识", "库", "knowledge", "wiki"],
    icon: "BookOpen",
  },
  {
    id: "knowledge-new",
    title: "新建知识",
    subtitle: "知识",
    href: "/knowledge/new",
    keywords: ["新建", "知识", "knowledge", "new"],
    icon: "Plus",
  },
  {
    id: "learning-methods",
    title: "学习方法",
    subtitle: "知识",
    href: "/learning-methods",
    keywords: ["学习", "方法", "learning", "method"],
    icon: "BookOpen",
  },
  {
    id: "learning-resources",
    title: "学习资源",
    subtitle: "知识",
    href: "/learning-resources",
    keywords: ["学习", "资源", "resource"],
    icon: "BookOpen",
  },

  // ────────────────────────── 个人 ──────────────────────────
  {
    id: "profile",
    title: "个人中心",
    subtitle: "个人",
    href: "/profile",
    keywords: ["个人", "中心", "profile", "我"],
    icon: "UserCircle",
  },
  {
    id: "profile-community",
    title: "我的社区",
    subtitle: "个人",
    href: "/profile/community",
    keywords: ["个人", "社区", "profile", "我的"],
    icon: "Users",
  },
  {
    id: "achievements",
    title: "成就墙",
    subtitle: "个人",
    href: "/achievements",
    keywords: ["成就", "墙", "achievements", "徽章"],
    icon: "Trophy",
  },
  {
    id: "notifications",
    title: "通知中心",
    subtitle: "个人",
    href: "/notifications",
    keywords: ["通知", "消息", "notifications"],
    icon: "Bell",
  },
  {
    id: "search",
    title: "搜索",
    subtitle: "个人",
    href: "/search",
    keywords: ["搜索", "search", "查找"],
    icon: "Search",
  },

  // ────────────────────────── 考研子 ──────────────────────────
  {
    id: "kaoyan-schools",
    title: "院校库",
    subtitle: "考研",
    href: "/kaoyan/schools",
    keywords: ["院校", "学校", "school", "考研"],
    icon: "GraduationCap",
  },
  {
    id: "kaoyan-mentors",
    title: "考研导师",
    subtitle: "考研",
    href: "/kaoyan/mentors",
    keywords: ["导师", "考研", "mentor"],
    icon: "Users",
  },
  {
    id: "kaoyan-compare",
    title: "院校对比",
    subtitle: "考研",
    href: "/kaoyan/compare",
    keywords: ["对比", "院校", "compare", "比较"],
    icon: "GitCompare",
  },
  {
    id: "kaoyan-predict",
    title: "考研预测",
    subtitle: "考研",
    href: "/kaoyan/predict",
    keywords: ["预测", "predict", "考研", "分数线"],
    icon: "TrendingUp",
  },
  {
    id: "kaoyan-strategy",
    title: "考研策略",
    subtitle: "考研",
    href: "/kaoyan/strategy",
    keywords: ["策略", "strategy", "考研", "资讯"],
    icon: "Target",
  },
  {
    id: "kaoyan-study-plans",
    title: "考研学习计划",
    subtitle: "考研",
    href: "/kaoyan/study-plans",
    keywords: ["学习", "计划", "考研", "study"],
    icon: "Swords",
  },
  {
    id: "kaoyan-dark-knowledge",
    title: "考研黑知识",
    subtitle: "考研",
    href: "/kaoyan/dark-knowledge",
    keywords: ["黑知识", "考研", "dark", "知识"],
    icon: "BookOpen",
  },
  {
    id: "kaoyan-community",
    title: "考研社区",
    subtitle: "考研",
    href: "/kaoyan/community",
    keywords: ["社区", "考研", "community"],
    icon: "Users",
  },
  {
    id: "kaoyan-community-posts",
    title: "考研社区 - 帖子",
    subtitle: "考研",
    href: "/kaoyan/community/posts",
    keywords: ["帖子", "考研", "社区", "posts"],
    icon: "MessageSquare",
  },
  {
    id: "kaoyan-community-posts-new",
    title: "发帖",
    subtitle: "考研",
    href: "/kaoyan/community/posts/new",
    keywords: ["发帖", "新帖", "考研", "new", "post"],
    icon: "Plus",
  },
  {
    id: "kaoyan-community-qa",
    title: "考研社区 - 问答",
    subtitle: "考研",
    href: "/kaoyan/community/qa",
    keywords: ["问答", "Q&A", "考研", "qa"],
    icon: "MessageSquare",
  },
  {
    id: "kaoyan-community-qa-new",
    title: "提问",
    subtitle: "考研",
    href: "/kaoyan/community/qa/new",
    keywords: ["提问", "问答", "new", "qa"],
    icon: "Plus",
  },
  {
    id: "kaoyan-community-tags",
    title: "考研社区 - 标签",
    subtitle: "考研",
    href: "/kaoyan/community/tags",
    keywords: ["标签", "tags", "考研", "社区"],
    icon: "Tag",
  },

  // ────────────────────────── 后台/管理 ──────────────────────────
  {
    id: "admin-home",
    title: "后台管理",
    subtitle: "管理",
    href: "/admin",
    keywords: ["后台", "管理", "admin", "首页"],
    icon: "LayoutDashboard",
  },
  {
    id: "admin-reports",
    title: "举报管理",
    subtitle: "管理",
    href: "/admin/reports",
    keywords: ["举报", "report", "管理", "admin"],
    icon: "Flag",
  },
  {
    id: "admin-users",
    title: "用户管理",
    subtitle: "管理",
    href: "/admin/users",
    keywords: ["用户", "封禁", "解封", "users", "admin"],
    icon: "Users",
  },
  {
    id: "admin-crawlers",
    title: "爬虫管理",
    subtitle: "管理",
    href: "/admin/crawlers",
    keywords: ["爬虫", "管理", "crawler", "admin"],
    icon: "Bug",
  },
  {
    id: "admin-moderation",
    title: "内容审核",
    subtitle: "管理",
    href: "/admin/moderation",
    keywords: ["审核", "moderation", "管理", "admin"],
    icon: "Shield",
  },
  {
    id: "admin-research-queue",
    title: "调研数据审核",
    subtitle: "管理",
    href: "/admin/research-queue",
    keywords: ["调研", "采集", "审核", "队列", "queue", "research", "admin"],
    icon: "Inbox",
  },
  {
    id: "admin-skills",
    title: "技能管理",
    subtitle: "管理",
    href: "/admin/skills",
    keywords: ["技能", "管理", "admin", "skills"],
    icon: "Network",
  },
  {
    id: "pipeline",
    title: "数据管道",
    subtitle: "管理",
    href: "/pipeline",
    keywords: ["管道", "pipeline", "数据"],
    icon: "GitBranch",
  },
  {
    id: "pipeline-ingest",
    title: "数据导入",
    subtitle: "管理",
    href: "/pipeline/ingest",
    keywords: ["导入", "ingest", "pipeline", "数据"],
    icon: "Download",
  },
  {
    id: "pipeline-sources",
    title: "数据源",
    subtitle: "管理",
    href: "/pipeline/sources",
    keywords: ["数据源", "source", "pipeline"],
    icon: "Database",
  },

  // ────────────────────────── 法律 ──────────────────────────
  {
    id: "legal",
    title: "法律文件",
    subtitle: "法律",
    href: "/legal",
    keywords: ["法律", "legal", "协议"],
    icon: "FileText",
  },
  {
    id: "legal-privacy",
    title: "隐私政策",
    subtitle: "法律",
    href: "/legal/privacy",
    keywords: ["隐私", "privacy", "政策"],
    icon: "FileText",
  },
  {
    id: "legal-terms",
    title: "用户协议",
    subtitle: "法律",
    href: "/legal/terms",
    keywords: ["用户", "协议", "terms"],
    icon: "FileText",
  },
  {
    id: "legal-cookie",
    title: "Cookie 政策",
    subtitle: "法律",
    href: "/legal/cookie",
    keywords: ["cookie", "政策"],
    icon: "FileText",
  },
];
